
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Aylin
 */
public class arsa extends javax.swing.JFrame {

    /**
     * Creates new form ARSA
     */
    public arsa() {
        initComponents();
    
        baglantiGiris();
        idarsa();
        idisletme();
       tabloisletme();
        tablo();
    }
    

     public void baglantiGiris(){
       try{
       Class.forName("com.mysql.jdbc.Driver");
     String bag="jdbc:mysql://localhost:3306/new_proje";
     String username="root";
     String sifre="684217";
     baglan= DriverManager.getConnection(bag,username,sifre);
    JOptionPane.showMessageDialog(null, "");
   
       }
       catch (ClassNotFoundException ex) {
            Logger.getLogger(yontoyuncuekleme.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(yontoyuncuekleme.class.getName()).log(Level.SEVERE, null, ex);
        }
       
   }
     Connection baglan; 
  PreparedStatement pat;
  ResultSet rs;
  int q,i;
   public void tabloisletme(){
        try {
            pat=baglan.prepareStatement("SELECT*FROM isletme");
 
              rs=pat.executeQuery();
            ResultSetMetaData stveri=rs.getMetaData();
            q=stveri.getColumnCount();
            DefaultTableModel RecordTable=(DefaultTableModel)jTable2.getModel();
                    RecordTable.setRowCount(0);
             while(rs.next()){
                 Vector sutunVeri=new Vector();
                 for(i =1;i<=q;i++){
                     sutunVeri.add(rs.getString("id"));
                     sutunVeri.add(rs.getString("isletmeSeviyesi"));
                     sutunVeri.add(rs.getString("isletmeFiyati"));
                     sutunVeri.add(rs.getString("isletmeBasTarihi"));
                     sutunVeri.add(rs.getString("SbtGelirOrani"));
                      sutunVeri.add(rs.getString("sbtGelirMiktari"));
                      sutunVeri.add(rs.getString("yöneticİsletmeÜcreti"));
                      sutunVeri.add(rs.getString("oyuncuİsletmeÜcreti"));
                      sutunVeri.add(rs.getString("isletmeKapasitesi"));
                      sutunVeri.add(rs.getString("oyuncu_id"));
                      sutunVeri.add(rs.getString("yonetici_id"));
                 }
                 RecordTable.addRow(sutunVeri);
                 
             }       
            
            
        } catch (SQLException ex) {
            Logger.getLogger(yontoyuncuekleme.class.getName()).log(Level.SEVERE, null, ex);
        }
      }
   public void idisletme() {
        try {
            pat=baglan.prepareStatement("SELECT id FROM isletme");
            rs=pat.executeQuery();
            txtiid.removeAllItems();
            while(rs.next()){
                txtiid.addItem(rs.getString(1));
            }
        } catch (SQLException ex) {
            Logger.getLogger(yontoyuncuekleme.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
      public void tablo(){
        try {
            pat=baglan.prepareStatement("SELECT*FROM arsa");
            rs=pat.executeQuery();
            ResultSetMetaData stveri=rs.getMetaData();
            q=stveri.getColumnCount();
            DefaultTableModel RecordTable=(DefaultTableModel)jTablo.getModel();
                    RecordTable.setRowCount(0);
             while(rs.next()){
                 Vector sutunVeri=new Vector();
                 for(i =1;i<=q;i++){
                     sutunVeri.add(rs.getString("id"));
                     sutunVeri.add(rs.getString("alanBoyut"));
                     sutunVeri.add(rs.getString("alanNo"));
                     sutunVeri.add(rs.getString("alanTür"));
                     sutunVeri.add(rs.getString("alan_sahibi"));
                      sutunVeri.add(rs.getString("isletme_id"));
                    
                 }
                 RecordTable.addRow(sutunVeri);
                 
             }       
            
            
        } catch (SQLException ex) {
            Logger.getLogger(yontoyuncuekleme.class.getName()).log(Level.SEVERE, null, ex);
        }
      }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tx_alanboyut = new javax.swing.JTextField();
        tx_alanno = new javax.swing.JTextField();
        tx_alantür = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablo = new javax.swing.JTable();
        tx_idisletme = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jbekle = new javax.swing.JButton();
        jbgüncelle = new javax.swing.JButton();
        jbdelete = new javax.swing.JButton();
        txtaid = new javax.swing.JComboBox<>();
        jbarama = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tx_alan_sahibi = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtiid = new javax.swing.JComboBox<>();
        jBisletmeara = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        tx_isletmeSeviyesi = new javax.swing.JTextField();
        tx_isletmeFiyati = new javax.swing.JTextField();
        tx_tarih = new javax.swing.JTextField();
        tx_SbtGelirOrani = new javax.swing.JTextField();
        tx_sbtGelirMiktari = new javax.swing.JTextField();
        tx_yöneticiİsletmeÜcreti = new javax.swing.JTextField();
        tx_oyuncuİsletmeÜcreti = new javax.swing.JTextField();
        tx_isletmeKapasitesi = new javax.swing.JTextField();
        tx_oyuncu_id = new javax.swing.JTextField();
        tx_yonetici_id = new javax.swing.JTextField();
        jButekle = new javax.swing.JButton();
        jbutguncelle = new javax.swing.JButton();
        jButdelete = new javax.swing.JButton();
        jBtablolar = new javax.swing.JButton();
        jBcıkıs = new javax.swing.JButton();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 133, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 117, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setText("alanTür:");

        jLabel3.setText("alanNo:");

        tx_alanboyut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tx_alanboyutActionPerformed(evt);
            }
        });

        tx_alanno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tx_alannoActionPerformed(evt);
            }
        });

        jLabel1.setText("alanboyut:");

        jTablo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "id", "alanBoyut", "alanNo", "alanTür", "alan_sahibi", "idisletme"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTablo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabloMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTablo);

        jLabel4.setText("idisletme:");

        jbekle.setText("EKLE");
        jbekle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbekleActionPerformed(evt);
            }
        });

        jbgüncelle.setText("GÜNCELLE");
        jbgüncelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbgüncelleActionPerformed(evt);
            }
        });

        jbdelete.setText("DELETE");
        jbdelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbdeleteActionPerformed(evt);
            }
        });

        txtaid.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jbarama.setText("ARAMA");
        jbarama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbaramaActionPerformed(evt);
            }
        });

        jLabel5.setText("arsa_id");

        jLabel6.setText("alan sahibi:");

        jLabel7.setText("isletme id:");

        txtiid.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jBisletmeara.setText("arama");
        jBisletmeara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBisletmearaActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "id", "isletmeS", "isletmeF", "isletmeBT", "sbtgeliroran", "sbtgelirmik", "yoneticisletmeü", "oyuncuisletmeü", "isletmeKapas", "oyuncu_id", "yonetici_id"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable2);

        jLabel8.setText("isletme seviyesi:");

        jLabel9.setText("isletmefiyati:");

        jLabel10.setText("isletmebastarihi:");

        jLabel11.setText("sbtgeliroran:");

        jLabel12.setText("sbtgelirmik:");

        jLabel13.setText("yöneticisletmeücret:");

        jLabel14.setText("oyuncuisletmeücret:");

        jLabel15.setText("isletmekapasitesi:");

        jLabel16.setText("oyuncu_id:");

        jLabel17.setText("yönetici_id:");

        tx_SbtGelirOrani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tx_SbtGelirOraniActionPerformed(evt);
            }
        });

        tx_sbtGelirMiktari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tx_sbtGelirMiktariActionPerformed(evt);
            }
        });

        jButekle.setText("ekle");
        jButekle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButekleActionPerformed(evt);
            }
        });

        jbutguncelle.setText("guncelle");
        jbutguncelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutguncelleActionPerformed(evt);
            }
        });

        jButdelete.setText("delete");
        jButdelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButdeleteActionPerformed(evt);
            }
        });

        jBtablolar.setText("tablolar");
        jBtablolar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtablolarActionPerformed(evt);
            }
        });

        jBcıkıs.setText("cıkıs");
        jBcıkıs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBcıkısActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(8, 8, 8)))
                                .addGap(62, 62, 62)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tx_alantür, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tx_alanno, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tx_alanboyut, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(64, 64, 64)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(68, 68, 68)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(tx_alan_sahibi, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(tx_idisletme, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(72, 72, 72)
                                        .addComponent(jbekle)
                                        .addGap(46, 46, 46)
                                        .addComponent(jbgüncelle)
                                        .addGap(53, 53, 53)
                                        .addComponent(jbdelete)
                                        .addGap(39, 39, 39)
                                        .addComponent(jBtablolar)
                                        .addGap(18, 18, 18)
                                        .addComponent(jBcıkıs))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jBisletmeara)
                                .addGap(418, 418, 418)
                                .addComponent(jLabel16)
                                .addGap(55, 55, 55)
                                .addComponent(tx_oyuncu_id, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(494, 494, 494)
                                .addComponent(jLabel17)
                                .addGap(55, 55, 55)
                                .addComponent(tx_yonetici_id, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbarama)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(txtaid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 1018, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtiid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(tx_sbtGelirMiktari, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(tx_SbtGelirOrani, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(tx_isletmeFiyati, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tx_tarih, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(238, 238, 238)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tx_isletmeSeviyesi, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(107, 107, 107)
                                .addComponent(jLabel13))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tx_isletmeKapasitesi, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButdelete))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(tx_oyuncuİsletmeÜcreti, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jbutguncelle))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(tx_yöneticiİsletmeÜcreti, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(114, 114, 114)
                                .addComponent(jButekle)))))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel13)
                    .addComponent(tx_isletmeSeviyesi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tx_yöneticiİsletmeÜcreti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButekle))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel14)
                            .addComponent(tx_isletmeFiyati, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tx_oyuncuİsletmeÜcreti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jbutguncelle)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(tx_tarih, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel10))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(tx_isletmeKapasitesi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel15)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jBisletmeara)
                                    .addComponent(jLabel11)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(tx_SbtGelirOrani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tx_oyuncu_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel12)
                                    .addComponent(tx_sbtGelirMiktari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(tx_yonetici_id))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtiid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addComponent(jLabel16)
                        .addGap(24, 24, 24)
                        .addComponent(jLabel17))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jButdelete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(77, 77, 77)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(tx_alanboyut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(tx_alanno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtaid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addComponent(jbarama)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(tx_alantür, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tx_alan_sahibi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tx_idisletme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbekle)
                            .addComponent(jbgüncelle)
                            .addComponent(jbdelete)
                            .addComponent(jBtablolar)
                            .addComponent(jBcıkıs))
                        .addGap(28, 28, 28))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tx_alanboyutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tx_alanboyutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tx_alanboyutActionPerformed

    private void tx_alannoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tx_alannoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tx_alannoActionPerformed

    private void jbekleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbekleActionPerformed
        // TODO add your handling code here:
         try {
            // TODO add your handling code here:
            String alanboyut=tx_alanboyut.getText();
            String alanno=tx_alanno.getText();
            String alantür=tx_alantür.getText();
            String alansahibi=tx_alan_sahibi.getText();
            String idisletme=tx_idisletme.getText();
        
            
           
            
            pat=baglan.prepareStatement("INSERT INTO arsa(alanBoyut,alanNo,alanTür,alan_sahibi,isletme_id) VALUES(?,?,?,?,?)");
            pat.setString(1,alanboyut);
            pat.setString(2, alanno);
            pat.setString(3, alantür);
            pat.setString(4, alansahibi);
            pat.setString(5,idisletme);
           
            int k=pat.executeUpdate();
             tablo();
            if(k==1){
                JOptionPane.showMessageDialog(this, "veri tabani eklemesi basarili");
               
                tx_alanboyut.setText("");
                tx_alanno.setText("");
                tx_alantür.setText("");
                 tx_alan_sahibi.setText("");
                tx_idisletme.setText("");
             
                  
            }
            else{
                JOptionPane.showMessageDialog(this, "veri tabani eklemesi basarisiz");
            }
               
        } catch (SQLException ex) {
            Logger.getLogger(yontoyuncuekleme.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbekleActionPerformed
   public void idarsa() {
        try {
            pat=baglan.prepareStatement("SELECT id FROM arsa");
            rs=pat.executeQuery();
            txtaid.removeAllItems();
            while(rs.next()){
                txtaid.addItem(rs.getString(1));
            }
        } catch (SQLException ex) {
            Logger.getLogger(yontoyuncuekleme.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void jbgüncelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbgüncelleActionPerformed
        // TODO add your handling code here:
          try {
            // TODO add your handling code here:
        String alanboyut=tx_alanboyut.getText();
            String alanno=tx_alanno.getText();
            String alantür=tx_alantür.getText();
             String alansahibi=tx_alan_sahibi.getText();
   
            String idisletme=tx_idisletme.getText();
            
            String arsaid=txtaid.getSelectedItem().toString();
            pat=baglan.prepareStatement("UPDATE arsa SET alanBoyut=?,alanNo=?,alanTür=?,alan_sahibi=?,isletme_id=? WHERE id=?");
            pat.setString(1,alanboyut);
            pat.setString(2, alanno);
            pat.setString(3, alantür);
            pat.setString(4, alansahibi);
            pat.setString(5,idisletme);
            pat.setString(6,arsaid);
        
              int k=pat.executeUpdate();
            if(k==1){
              JOptionPane.showMessageDialog(this, "kayit basariyla guncellendi");
           tablo();
               
             tx_alanboyut.setText("");
                tx_alanno.setText("");
                tx_alantür.setText("");
                tx_alan_sahibi.setText("");
                tx_idisletme.setText("");
                 tx_alanboyut.requestFocus();
                idarsa();
                
                  
            }
        } catch (SQLException ex) {
            Logger.getLogger(yontoyuncuekleme.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbgüncelleActionPerformed

    private void jbaramaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbaramaActionPerformed
        // TODO add your handling code here:
      
    
   
           try {
            // TODO add your handling code here:
            String arsaid=txtaid.getSelectedItem().toString();
            pat=baglan.prepareStatement("SELECT*FROM arsa WHERE id=?");
            pat.setString(1, arsaid);
            
            rs=pat.executeQuery();
          
            if(rs.next()==true){
               tx_alanboyut.setText(rs.getString(2));
                tx_alanno.setText(rs.getString(3));
               tx_alantür.setText(rs.getString(4));
                tx_alan_sahibi.setText(rs.getString(5));
                 tx_idisletme.setText(rs.getString(6));
                 
                 
              
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(yontoyuncuekleme.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbaramaActionPerformed

    private void jTabloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabloMouseClicked
        // TODO add your handling code here:
            DefaultTableModel RecordTable=(DefaultTableModel)jTablo.getModel();
        int satirSec=jTablo.getSelectedRow();
 
       tx_alanboyut.setText(RecordTable.getValueAt(satirSec, 1).toString());
        tx_alanno.setText(RecordTable.getValueAt(satirSec, 2).toString());
        tx_alantür.setText(RecordTable.getValueAt(satirSec, 3).toString());
         tx_alan_sahibi.setText(RecordTable.getValueAt(satirSec, 4).toString());
        tx_idisletme.setText(RecordTable.getValueAt(satirSec, 5).toString());
      
    }//GEN-LAST:event_jTabloMouseClicked

    private void jbdeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbdeleteActionPerformed
        // TODO add your handling code here:
           DefaultTableModel RecordTable=(DefaultTableModel)jTablo.getModel();
        int satirSec=jTablo.getSelectedRow();
      
      
              try {
             int id=Integer.parseInt(RecordTable.getValueAt(satirSec, 0).toString());
       int delete=JOptionPane.showConfirmDialog(null,"silinsin","silme islemi",JOptionPane.YES_NO_OPTION);
        if(delete==JOptionPane.YES_OPTION){
                  pat=baglan.prepareStatement("DELETE FROM arsa WHERE id=?");
                  pat.setInt(1, id);
                  pat.execute();
                  tablo();
                  tx_alanboyut.setText("");
                  tx_alanboyut.requestFocus();
                  tx_alanno.setText("");
                  tx_alantür.setText("");
                   tx_alan_sahibi.setText("");
                  tx_idisletme.setText("");
                
                  
                
        } 
              } catch (SQLException ex) {
                  Logger.getLogger(yontoyuncuekleme.class.getName()).log(Level.SEVERE, null, ex);
              }
    }//GEN-LAST:event_jbdeleteActionPerformed

    private void jBisletmearaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBisletmearaActionPerformed
        // TODO add your handling code here:
           try {
            // TODO add your handling code here:
            String isletmeid=txtiid.getSelectedItem().toString();
            pat=baglan.prepareStatement("SELECT*FROM isletme WHERE id=?");
            pat.setString(1, isletmeid);
            
            rs=pat.executeQuery();
          
            if(rs.next()==true){
               tx_isletmeSeviyesi.setText(rs.getString(2));
                tx_isletmeFiyati.setText(rs.getString(3));
               //jDate1.setDateFormatString(rs.getString(4));
               tx_tarih.setText(rs.getString(4));
                 tx_SbtGelirOrani.setText(rs.getString(5));
                  tx_sbtGelirMiktari.setText(rs.getString(6));
                   tx_yöneticiİsletmeÜcreti.setText(rs.getString(7));
                    tx_oyuncuİsletmeÜcreti.setText(rs.getString(8));
                     tx_isletmeKapasitesi.setText(rs.getString(9));
                      tx_oyuncu_id.setText(rs.getString(10));
                 tx_yonetici_id.setText(rs.getString(11));
                 
              
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(yontoyuncuekleme.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jBisletmearaActionPerformed

    private void tx_SbtGelirOraniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tx_SbtGelirOraniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tx_SbtGelirOraniActionPerformed

    private void tx_sbtGelirMiktariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tx_sbtGelirMiktariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tx_sbtGelirMiktariActionPerformed

    private void jButekleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButekleActionPerformed
        // TODO add your handling code here:
           try {
            // TODO add your handling code here:
           
            String isletmeSeviyesi=tx_isletmeSeviyesi.getText();
            String isletmeFiyati=tx_isletmeFiyati.getText();
            
            /*SimpleDateFormat dateformat=new SimpleDateFormat("yyyy-MM-dd");
            String isletmeBasTarihi=dateformat.format(jDate1.getDate());*/
            
            String isletmeBasTarihi=tx_tarih.getText();
            String SbtGelirOrani=tx_SbtGelirOrani.getText();
            String sbtGelirMiktari=tx_sbtGelirMiktari.getText();
            String yöneticiİsletmeÜcreti=tx_yöneticiİsletmeÜcreti.getText();
            String oyuncuİsletmeÜcreti=tx_oyuncuİsletmeÜcreti.getText();
            String isletmeKapasitesi=tx_isletmeKapasitesi.getText();
            String oyuncu_id=tx_oyuncu_id.getText();
            String yonetici_id=tx_yonetici_id.getText();
           
            
            pat=baglan.prepareStatement("INSERT INTO isletme(isletmeSeviyesi,isletmeFiyati,isletmeBasTarihi,SbtGelirOrani,sbtGelirMiktari,yöneticİsletmeÜcreti,oyuncuİsletmeÜcreti,isletmeKapasitesi,oyuncu_id,yonetici_id) VALUES(?,?,?,?,?,?,?,?,?,?)");
            pat.setString(1,isletmeSeviyesi);
            pat.setString(2, isletmeFiyati);
            pat.setString(3, isletmeBasTarihi);
            pat.setString(4,SbtGelirOrani);
            pat.setString(5,sbtGelirMiktari);
             pat.setString(6,yöneticiİsletmeÜcreti);
              pat.setString(7,oyuncuİsletmeÜcreti);
               pat.setString(8,isletmeKapasitesi); 
               pat.setString(9,oyuncu_id);
                pat.setString(10,yonetici_id);
               
            int k=pat.executeUpdate();
             tablo();
            if(k==1){
                JOptionPane.showMessageDialog(this, "veri tabani eklemesi basarili");
                tabloisletme();
                tx_isletmeSeviyesi.setText("");
                tx_isletmeFiyati.setText("");
                tx_isletmeFiyati.setText("");
                //jDate1.setDateFormatString("");
                 tx_tarih.setText("");
                tx_SbtGelirOrani.setText("");
                tx_sbtGelirMiktari.setText("");
                tx_yöneticiİsletmeÜcreti.setText("");
                tx_oyuncuİsletmeÜcreti.setText("");
                tx_isletmeKapasitesi.setText("");
                tx_oyuncu_id.setText("");                
                  tx_yonetici_id.setText("");                                                               
                                                                             
                  
            }
            else{
                JOptionPane.showMessageDialog(this, "veri tabani eklemesi basarisiz");
            }
               
        } catch (SQLException ex) {
            Logger.getLogger(yontoyuncuekleme.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButekleActionPerformed

    private void jbutguncelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutguncelleActionPerformed
        // TODO add your handling code here:
          try {
            // TODO add your handling code here:
       String isletmeSeviyesi=tx_isletmeSeviyesi.getText();
            String isletmeFiyati=tx_isletmeFiyati.getText();
           /* SimpleDateFormat dateformat=new SimpleDateFormat("yyyy-MM-dd");
            String isletmeBasTarihi=dateformat.format(jDate1.getDate());*/
             String isletmeBasTarihi=tx_tarih.getText();
            String SbtGelirOrani=tx_SbtGelirOrani.getText();
            String sbtGelirMiktari=tx_sbtGelirMiktari.getText();
            String yöneticiİsletmeÜcreti=tx_yöneticiİsletmeÜcreti.getText();
            String oyuncuİsletmeÜcreti=tx_oyuncuİsletmeÜcreti.getText();
            String isletmeKapasitesi=tx_isletmeKapasitesi.getText();
            String oyuncu_id=tx_oyuncu_id.getText();
            String yonetici_id=tx_yonetici_id.getText();
            
            String isletmeid=txtiid.getSelectedItem().toString();
             pat=baglan.prepareStatement("UPDATE isletme SET isletmeSeviyesi=?,isletmeFiyati=?,isletmeBasTarihi=?,SbtGelirOrani=?,sbtGelirMiktari=?,yöneticİsletmeÜcreti=?,oyuncuİsletmeÜcreti=?,isletmeKapasitesi=?,oyuncu_id=?,yonetici_id=? WHERE id=?");
             pat.setString(1,isletmeSeviyesi);
            pat.setString(2, isletmeFiyati);
            pat.setString(3, isletmeBasTarihi);
            pat.setString(4,SbtGelirOrani);
            pat.setString(5,sbtGelirMiktari);
             pat.setString(6,yöneticiİsletmeÜcreti);
              pat.setString(7,oyuncuİsletmeÜcreti);
               pat.setString(8,isletmeKapasitesi); 
               pat.setString(9,oyuncu_id);
               pat.setString(10,yonetici_id);
            pat.setString(11,isletmeid);
            
              int k=pat.executeUpdate();
            if(k==1){
              JOptionPane.showMessageDialog(this, "kayit basariyla guncellendi");
           tablo();
                 tx_isletmeSeviyesi.setText("");
                tx_isletmeFiyati.setText("");
                tx_isletmeFiyati.setText("");
               // jDate1.setDateFormatString("");
               tx_tarih.setText("");
                tx_SbtGelirOrani.setText("");
                tx_sbtGelirMiktari.setText("");
                tx_yöneticiİsletmeÜcreti.setText("");
                tx_oyuncuİsletmeÜcreti.setText("");
                tx_isletmeKapasitesi.setText("");
                tx_oyuncu_id.setText("");   
            tx_yonetici_id.setText("");
                  tx_isletmeSeviyesi.requestFocus();
                idisletme();
                
                  
            }
        } catch (SQLException ex) {
            Logger.getLogger(yontoyuncuekleme.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbutguncelleActionPerformed

    private void jButdeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButdeleteActionPerformed
        DefaultTableModel RecordTable=(DefaultTableModel)jTable2.getModel();
        int satirSec=jTablo.getSelectedRow();
      
      
              try {
             int id=Integer.parseInt(RecordTable.getValueAt(satirSec, 0).toString());
       int delete=JOptionPane.showConfirmDialog(null,"silinsin","silme islemi",JOptionPane.YES_NO_OPTION);
        if(delete==JOptionPane.YES_OPTION){
                  pat=baglan.prepareStatement("DELETE FROM isletme WHERE id=?");
                  pat.setInt(1, id);
                  pat.execute();
                  tablo();
                    tx_isletmeSeviyesi.setText("");
                tx_isletmeFiyati.setText("");
                tx_isletmeFiyati.setText("");
                //jDate1.setDateFormatString("");
                tx_tarih.setText("");
                tx_SbtGelirOrani.setText("");
                tx_sbtGelirMiktari.setText("");
                tx_yöneticiİsletmeÜcreti.setText("");
                tx_oyuncuİsletmeÜcreti.setText("");
                tx_isletmeKapasitesi.setText("");
                tx_oyuncu_id.setText("");  
                 tx_yonetici_id.setText(""); 
                  
                
        } 
              } catch (SQLException ex) {
                  Logger.getLogger(yontoyuncuekleme.class.getName()).log(Level.SEVERE, null, ex);
              }        // TODO add your handling code here:
    }//GEN-LAST:event_jButdeleteActionPerformed

    private void jBtablolarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtablolarActionPerformed
        // TODO add your handling code here:
        new tablolar().setVisible(true);
        
        
    }//GEN-LAST:event_jBtablolarActionPerformed

    private void jBcıkısActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBcıkısActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jBcıkısActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(arsa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(arsa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(arsa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(arsa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new arsa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBcıkıs;
    private javax.swing.JButton jBisletmeara;
    private javax.swing.JButton jBtablolar;
    private javax.swing.JButton jButdelete;
    private javax.swing.JButton jButekle;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTablo;
    private javax.swing.JButton jbarama;
    private javax.swing.JButton jbdelete;
    private javax.swing.JButton jbekle;
    private javax.swing.JButton jbgüncelle;
    private javax.swing.JButton jbutguncelle;
    private javax.swing.JTextField tx_SbtGelirOrani;
    private javax.swing.JTextField tx_alan_sahibi;
    private javax.swing.JTextField tx_alanboyut;
    private javax.swing.JTextField tx_alanno;
    private javax.swing.JTextField tx_alantür;
    private javax.swing.JTextField tx_idisletme;
    private javax.swing.JTextField tx_isletmeFiyati;
    private javax.swing.JTextField tx_isletmeKapasitesi;
    private javax.swing.JTextField tx_isletmeSeviyesi;
    private javax.swing.JTextField tx_oyuncu_id;
    private javax.swing.JTextField tx_oyuncuİsletmeÜcreti;
    private javax.swing.JTextField tx_sbtGelirMiktari;
    private javax.swing.JTextField tx_tarih;
    private javax.swing.JTextField tx_yonetici_id;
    private javax.swing.JTextField tx_yöneticiİsletmeÜcreti;
    private javax.swing.JComboBox<String> txtaid;
    private javax.swing.JComboBox<String> txtiid;
    // End of variables declaration//GEN-END:variables
}
