
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Aylin
 */
public class emlakislem extends javax.swing.JFrame {

    /**
     * Creates new form emlakislem
     */
    public emlakislem() {
        initComponents();
        connection();
        idoyuncu();
        idemlak();
        idemlakislem();
        tabloemlakislem();
    }
      Connection baglan; 
  PreparedStatement pat;
  ResultSet rs;
  int q,i;
       public void connection(){
       try{
       Class.forName("com.mysql.jdbc.Driver");
     String bag="jdbc:mysql://localhost:3306/new_proje";
     String username="root";
     String sifre="684217";
     baglan= DriverManager.getConnection(bag,username,sifre);
    JOptionPane.showMessageDialog(null, "veri tabani baglantisi basarili");
   
       }
       catch (ClassNotFoundException ex) {
            Logger.getLogger(yontoyuncuekleme.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(yontoyuncuekleme.class.getName()).log(Level.SEVERE, null, ex);
        }
       
   }
          public void idoyuncu() {
        try {
            pat=baglan.prepareStatement("SELECT id FROM oyuncu");
            rs=pat.executeQuery();
            txtoid.removeAllItems();
            while(rs.next()){
                txtoid.addItem(rs.getString(1));
            }
        } catch (SQLException ex) {
            Logger.getLogger(yontoyuncuekleme.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
          public void idemlak() {
        try {
            pat=baglan.prepareStatement("SELECT id FROM emlak");
            rs=pat.executeQuery();
            txteid.removeAllItems();
            while(rs.next()){
                txteid.addItem(rs.getString(1));
            }
        } catch (SQLException ex) {
            Logger.getLogger(yontoyuncuekleme.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
     public void idemlakislem() {
        try {
            pat=baglan.prepareStatement("SELECT id FROM emlakislem");
            rs=pat.executeQuery();
            txteiid.removeAllItems();
            while(rs.next()){
                txteiid.addItem(rs.getString(1));
            }
        } catch (SQLException ex) {
            Logger.getLogger(yontoyuncuekleme.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
     
     public void tabloemlakislem(){
        try {
            pat=baglan.prepareStatement("SELECT*FROM emlakislem");
 
              rs=pat.executeQuery();
            ResultSetMetaData stveri=rs.getMetaData();
            q=stveri.getColumnCount();
            DefaultTableModel RecordTable=(DefaultTableModel)jTemlakislem.getModel();
                    RecordTable.setRowCount(0);
             while(rs.next()){
                 Vector sutunVeri=new Vector();
                 for(i =1;i<=q;i++){
                     sutunVeri.add(rs.getString("id"));
                     sutunVeri.add(rs.getString("kiralik_isletme_fiyat"));
                     sutunVeri.add(rs.getString("kira_suresi"));
                     sutunVeri.add(rs.getString("kira_baslangic_t"));
                     sutunVeri.add(rs.getString("kira_bitis_t"));
                    sutunVeri.add(rs.getString("satis_t"));
                    sutunVeri.add(rs.getString("emlak_id"));
                 }
                 RecordTable.addRow(sutunVeri);
                 
             }       
            
            
        } catch (SQLException ex) {
            Logger.getLogger(yontoyuncuekleme.class.getName()).log(Level.SEVERE, null, ex);
        }
      }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tx_kiralik_isletme_fiyat = new javax.swing.JTextField();
        tx_kira_süresi = new javax.swing.JTextField();
        tx_emlak_id = new javax.swing.JTextField();
        jBekle = new javax.swing.JButton();
        jBanlasma = new javax.swing.JButton();
        jBdelete = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txteiid = new javax.swing.JComboBox<>();
        jBara = new javax.swing.JButton();
        tx_kira_baslangic_t = new javax.swing.JTextField();
        tx_kira_bitis_t = new javax.swing.JTextField();
        tx_satis_t = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        tx_ad = new javax.swing.JTextField();
        tx_soyad = new javax.swing.JTextField();
        tx_kullaniciAdi = new javax.swing.JTextField();
        tx_sifre = new javax.swing.JTextField();
        tx_paraMik = new javax.swing.JTextField();
        tx_esyaMik = new javax.swing.JTextField();
        tx_yemekMik = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        tx_emlak_komisyonu = new javax.swing.JTextField();
        tx_g_para_gideri = new javax.swing.JTextField();
        tx_isletme_id = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txteid = new javax.swing.JComboBox<>();
        jBemlakara = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        txtoid = new javax.swing.JComboBox<>();
        jBoyunculistele = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        tx_calisma_bas_t = new javax.swing.JTextField();
        tx_calisma_bit_t = new javax.swing.JTextField();
        tx_calisma_s = new javax.swing.JTextField();
        tx_calisma_gun_s = new javax.swing.JTextField();
        tx_gunluk_k_para = new javax.swing.JTextField();
        tx_kazanc = new javax.swing.JTextField();
        jBhesapla = new javax.swing.JButton();
        jBkiralama = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        tx_kira_ucreti = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        tx_toplamkira_ucreti = new javax.swing.JTextField();
        jBtemizle = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTemlakislem = new javax.swing.JTable();
        jButoyuncutabl = new javax.swing.JButton();
        jBcıkıs = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("kiralik_isletme_fiyati:");

        jLabel2.setText("kira_süresi:");

        jLabel3.setText("kira_baslangic_t:");

        jLabel4.setText("kira_bitis_t");

        jLabel5.setText("satis_t:");

        jLabel6.setText("emlak_id:");

        tx_emlak_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tx_emlak_idActionPerformed(evt);
            }
        });

        jBekle.setText("EKLE");
        jBekle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBekleActionPerformed(evt);
            }
        });

        jBanlasma.setText("ANLAŞMA");
        jBanlasma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBanlasmaActionPerformed(evt);
            }
        });

        jBdelete.setText("DELETE");
        jBdelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBdeleteActionPerformed(evt);
            }
        });

        jLabel7.setText("emlakislemid:");

        txteiid.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jBara.setText("ARA");
        jBara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBaraActionPerformed(evt);
            }
        });

        tx_kira_bitis_t.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tx_kira_bitis_tActionPerformed(evt);
            }
        });

        tx_satis_t.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tx_satis_tActionPerformed(evt);
            }
        });

        jLabel8.setText("AD:");

        jLabel9.setText("SOYAD:");

        jLabel10.setText("KULLANİCİ A:");

        jLabel11.setText("SİFRE:");

        jLabel12.setText("YEMEK MİK:");

        jLabel13.setText("ESYA MİK:");

        jLabel14.setText("PARA MİK:");

        tx_soyad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tx_soyadActionPerformed(evt);
            }
        });

        jLabel15.setText("emlak_komisyonu:");

        jLabel16.setText("g_para_gideri:");

        jLabel17.setText("isletme id:");

        jLabel18.setText("emlak id:");

        txteid.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jBemlakara.setText("ara");
        jBemlakara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBemlakaraActionPerformed(evt);
            }
        });

        jLabel19.setText("oyuncu id:");

        txtoid.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jBoyunculistele.setText("listele");
        jBoyunculistele.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBoyunculisteleActionPerformed(evt);
            }
        });

        jLabel20.setText("Calisma_Bas_t:");

        jLabel21.setText("Calisma_Bit_t:");

        jLabel22.setText("Calisma_saat:");

        jLabel23.setText("Calisma_gün_s:");

        jLabel24.setText("Günlük_k_para:");

        jLabel25.setText("Toplam para:");

        tx_calisma_bas_t.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tx_calisma_bas_tActionPerformed(evt);
            }
        });

        tx_calisma_gun_s.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tx_calisma_gun_sActionPerformed(evt);
            }
        });

        tx_gunluk_k_para.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tx_gunluk_k_paraActionPerformed(evt);
            }
        });

        tx_kazanc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tx_kazancActionPerformed(evt);
            }
        });

        jBhesapla.setText("HESAPLAMA");
        jBhesapla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBhesaplaActionPerformed(evt);
            }
        });

        jBkiralama.setText("KİRALAMA VE KOMİSYON ALMA");
        jBkiralama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBkiralamaActionPerformed(evt);
            }
        });

        jLabel26.setText(" Kira Ücreti:");

        jLabel27.setText("ToplamKiraÜcreti:");

        jBtemizle.setText("TEMİZLE");
        jBtemizle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtemizleActionPerformed(evt);
            }
        });

        jTemlakislem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "id", "kiralik_isletme_fiyati", "kira_süresi", "kira_baslangic_t", "kira_bitis_t", "satis_t", "emlak_id"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTemlakislem);

        jButoyuncutabl.setText("oyuncutablosugoruntule");
        jButoyuncutabl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButoyuncutablActionPerformed(evt);
            }
        });

        jBcıkıs.setText("cıkıs");
        jBcıkıs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBcıkısActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(tx_sifre, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(46, 46, 46)
                                        .addComponent(tx_ad, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tx_kullaniciAdi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tx_soyad, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(41, 41, 41)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tx_gunluk_k_para, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tx_calisma_gun_s, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tx_calisma_bas_t, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tx_calisma_bit_t, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tx_calisma_s, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(28, 28, 28)
                                .addComponent(tx_kiralik_isletme_fiyat, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jBara)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(tx_emlak_id, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(tx_kira_bitis_t, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(tx_kira_baslangic_t, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(tx_satis_t, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel26)
                                                .addGap(42, 42, 42)
                                                .addComponent(tx_kira_ucreti, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(tx_toplamkira_ucreti, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(14, 14, 14)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(tx_kira_süresi, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(38, 38, 38))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tx_esyaMik, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tx_yemekMik, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tx_paraMik, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jBoyunculistele)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel25)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tx_kazanc, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(122, 122, 122)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(286, 286, 286)
                                .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)))
                        .addGap(187, 187, 187)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(32, 32, 32)
                                    .addComponent(tx_isletme_id, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jBemlakara))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(jLabel16)
                                            .addGap(28, 28, 28)
                                            .addComponent(tx_g_para_gideri, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel15)
                                            .addGap(18, 18, 18)
                                            .addComponent(tx_emlak_komisyonu, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(26, 26, 26)
                                    .addComponent(jLabel18)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txteid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jBkiralama)
                                .addGap(18, 18, 18)
                                .addComponent(jBtemizle)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBdelete)
                            .addComponent(jBekle))
                        .addGap(59, 59, 59))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBanlasma)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBhesapla)
                .addGap(97, 97, 97))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(txtoid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButoyuncutabl)
                        .addGap(75, 75, 75)
                        .addComponent(jBcıkıs)
                        .addGap(88, 88, 88)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txteiid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 821, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(427, 427, 427)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txteiid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBcıkıs))
                        .addGap(18, 18, 18)
                        .addComponent(jBara))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(tx_ad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15)
                            .addComponent(tx_emlak_komisyonu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tx_kiralik_isletme_fiyat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel20)
                            .addComponent(tx_calisma_bas_t, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(tx_soyad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel16)
                                    .addComponent(tx_g_para_gideri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel21)
                                    .addComponent(tx_calisma_bit_t, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tx_kira_süresi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10)
                                    .addComponent(tx_kullaniciAdi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel17)
                                    .addComponent(tx_isletme_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel22)
                                    .addComponent(tx_calisma_s, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3)
                                    .addComponent(tx_kira_baslangic_t, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel11)
                                    .addComponent(tx_sifre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel23)
                                    .addComponent(tx_calisma_gun_s, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tx_kira_bitis_t, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jBanlasma)
                                    .addComponent(jBhesapla)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txteid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel18))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jBemlakara)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel12)
                                    .addComponent(tx_yemekMik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel24)
                                    .addComponent(tx_gunluk_k_para, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5)
                                    .addComponent(tx_satis_t, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel13)
                                    .addComponent(tx_esyaMik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel25)
                                    .addComponent(tx_kazanc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(46, 46, 46)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel14)
                                    .addComponent(tx_paraMik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel27)
                                    .addComponent(tx_toplamkira_ucreti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jBkiralama)
                                    .addComponent(jBtemizle))
                                .addGap(8, 8, 8)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tx_emlak_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel26)
                                    .addComponent(tx_kira_ucreti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jBekle))
                                .addGap(18, 18, 18)
                                .addComponent(jBdelete)))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(txtoid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButoyuncutabl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBoyunculistele)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tx_emlak_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tx_emlak_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tx_emlak_idActionPerformed

    private void jBaraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBaraActionPerformed
        // TODO add your handling code here:
            try {
            // TODO add your handling code here:
            String emlakislemid=txteiid.getSelectedItem().toString();
            pat=baglan.prepareStatement("SELECT*FROM emlakislem WHERE id=?");
            pat.setString(1, emlakislemid);
            
            rs=pat.executeQuery();
          
            if(rs.next()==true){
               tx_kiralik_isletme_fiyat.setText(rs.getString(2));
                tx_kira_süresi.setText(rs.getString(3));
               tx_kira_baslangic_t.setText(rs.getString(4));
                tx_kira_bitis_t.setText(rs.getString(5));
                 tx_satis_t.setText(rs.getString(6));
                tx_emlak_id.setText(rs.getString(7));
                 
                 
              
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(yontoyuncuekleme.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jBaraActionPerformed
public void veriTemizle(){
        tx_kiralik_isletme_fiyat.setText("");
               tx_kira_süresi.setText("");
             tx_kira_baslangic_t.setText("");
                 tx_kira_bitis_t.setText(""); 
                 tx_satis_t.setText("");
                tx_emlak_id.setText("");
                tx_kiralik_isletme_fiyat.requestFocus();
                idemlakislem();
                
                tx_ad.setText("");
                tx_soyad.setText("");
                tx_kullaniciAdi.setText("");
                tx_sifre.setText("");
                tx_yemekMik.setText("");
                tx_esyaMik.setText("");
                tx_paraMik.setText("");
                  tx_calisma_bas_t.setText("");
                   tx_calisma_bit_t.setText("");
                    tx_calisma_s.setText("");
                     tx_calisma_gun_s.setText("");
                      tx_gunluk_k_para.setText("");
                         tx_ad.requestFocus();
               idoyuncu();
                  tx_emlak_komisyonu.setText("");
               tx_g_para_gideri.setText("");
                tx_isletme_id.setText("");
                tx_emlak_komisyonu.requestFocus();
                idemlak();
}
    private void jBekleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBekleActionPerformed
        // TODO add your handling code here:
          try {
            // TODO add your handling code here:
            String kiralik_isletme_fiyat=tx_kiralik_isletme_fiyat.getText();
            String kira_suresi=tx_kira_süresi.getText();
            /*SimpleDateFormat dateformat=new SimpleDateFormat("yyyy-MM-dd");
            String kira_baslangic_t=dateformat.format(jDateKBaslangic.getDate());
            
             SimpleDateFormat dateformat1=new SimpleDateFormat("yyyy-MM-dd");
            String kira_bitis_t=dateformat1.format(jDateKBitis.getDate());
            
             SimpleDateFormat dateformat2=new SimpleDateFormat("yyyy-MM-dd");
            String satis_t=dateformat2.format(jDateSatis.getDate());*/
            String kira_baslangic_t=tx_kira_baslangic_t.getText();
             String kira_bitis_t=tx_kira_bitis_t.getText();
              String satis_t=tx_satis_t.getText();
            String emlak_id=tx_emlak_id.getText();
   
           
      
            pat=baglan.prepareStatement("INSERT INTO emlakislem(kiralik_isletme_fiyat,kira_suresi,kira_baslangic_t,kira_bitis_t,satis_t,emlak_id) VALUES(?,?,?,?,?,?)");
            pat.setString(1,kiralik_isletme_fiyat);
            pat.setString(2, kira_suresi);
            pat.setString(3, kira_baslangic_t);
             pat.setString(4, kira_bitis_t);
              pat.setString(5, satis_t);
               pat.setString(6,emlak_id);
            
           
            int k=pat.executeUpdate();
             tabloemlakislem();
            if(k==1){
                JOptionPane.showMessageDialog(this, "veri tabani eklemesi basarili");
               
             
                  
            }
            else{
                JOptionPane.showMessageDialog(this, "veri tabani eklemesi basarisiz");
            }
               
        } catch (SQLException ex) {
            Logger.getLogger(yontoyuncuekleme.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jBekleActionPerformed

   public void emlakislem_anlasma(){
          String kiralik_isletme_fiyat=tx_kiralik_isletme_fiyat.getText();
            String kira_suresi=tx_kira_süresi.getText();
             String kira_baslangic_t=tx_kira_baslangic_t.getText();
             String kira_bitis_t=tx_kira_bitis_t.getText();
              String satis_t=tx_satis_t.getText();
            String emlak_id=tx_emlak_id.getText();
            
            String emlakislemid=txteiid.getSelectedItem().toString();
        try {
            pat=baglan.prepareStatement("UPDATE emlakislem SET kiralik_isletme_fiyat=?,kira_suresi=?,kira_baslangic_t=?,kira_bitis_t=?,satis_t=?,emlak_id=? WHERE id=?");
              pat.setString(1,kiralik_isletme_fiyat);
            pat.setString(2, kira_suresi);
            pat.setString(3, kira_baslangic_t);
             pat.setString(4, kira_bitis_t);
             pat.setString(5, satis_t);
             pat.setString(6,emlak_id);
            pat.setString(7,emlakislemid);
             int k=pat.executeUpdate();
               tabloemlakislem();
            if(k==1){
              JOptionPane.showMessageDialog(this, "kayit basariyla guncellendi");
          
                   
            }
        } catch (SQLException ex) {
            Logger.getLogger(emlakislem.class.getName()).log(Level.SEVERE, null, ex);
        }
           
       
   }
   public void emlak_anlasma(){
         String emlak_komisyonu=tx_emlak_komisyonu.getText();
            String g_para_gideri=tx_g_para_gideri.getText();
             String isletme_id=tx_isletme_id.getText();
          
            
            String emlakid=txteid.getSelectedItem().toString();
        try {
            pat=baglan.prepareStatement("UPDATE emlak SET emlak_komisyonu=?,g_para_gideri=?,isletme_id=? WHERE id=?");
              pat.setString(1,emlak_komisyonu);
            pat.setString(2, g_para_gideri);
            pat.setString(3, isletme_id);
            
            pat.setString(4,emlakid);
             int k=pat.executeUpdate();
              // tabloemlakislem();
            if(k==1){
              JOptionPane.showMessageDialog(this, "kayit basariyla guncellendi");
          
                
            }
        } catch (SQLException ex) {
            Logger.getLogger(emlakislem.class.getName()).log(Level.SEVERE, null, ex);
        }
       
   }
    private void jBanlasmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBanlasmaActionPerformed
        // TODO add your handling code here:
             try {
            // TODO add your handling code here:
        
            emlakislem_anlasma();
            emlak_anlasma();
                //oyuncu kismi icinnn
               String ad=tx_ad.getText();
            String soyad=tx_soyad.getText();
            String kullaniciAdi=tx_kullaniciAdi.getText();
            String sifre=String.valueOf(tx_sifre.getText());
            String yemekMik=tx_yemekMik.getText();
            String esyaMik=tx_esyaMik.getText();
            String paraMik=tx_paraMik.getText();
            
      String calisma_bas_t=tx_calisma_bas_t.getText();
       String calisma_bit_t=tx_calisma_bit_t.getText();
             String calisma_s=tx_calisma_s.getText();
             String calisma_gun_s = tx_calisma_gun_s.getText();
            String gunluk_k_para= tx_gunluk_k_para.getText();
             String oyuncuid=txtoid.getSelectedItem().toString();
             
       
        
               pat=baglan.prepareStatement("UPDATE oyuncu SET oyuncuAd=?,oyuncuSoyad=?,kullaniciAdi=?,sifre=?,yemekMik=?,esyaMik=?,paraMik=?,calisma_bas_t=?,calisma_bitis_t=?,calisma_saat=?,calisma_gün_s=?,gunluk_k_para=? WHERE id=?");
            pat.setString(1, ad);
            pat.setString(2, soyad);
            pat.setString(3, kullaniciAdi);
            pat.setString(4,sifre);
             pat.setString(5,yemekMik );
            pat.setString(6,esyaMik );
            pat.setString(7,paraMik);
             pat.setString(8,calisma_bas_t);
              pat.setString(9,calisma_bit_t);
               pat.setString(10,calisma_s);
                pat.setString(11,calisma_gun_s );
                pat.setString(12,gunluk_k_para );
                  pat.setString(13,oyuncuid );
              int k=pat.executeUpdate();
               tabloemlakislem();
            if(k==1){
              JOptionPane.showMessageDialog(this, "kayit basariyla guncellendi");
          
                
                
                  
            }
        } catch (SQLException ex) {
            Logger.getLogger(yontoyuncuekleme.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jBanlasmaActionPerformed

    private void jBdeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBdeleteActionPerformed
        // TODO add your handling code here:
                  DefaultTableModel RecordTable=(DefaultTableModel)jTemlakislem.getModel();
        int satirSec=jTemlakislem.getSelectedRow();
      
      
              try {
             int id=Integer.parseInt(RecordTable.getValueAt(satirSec, 0).toString());
       int delete=JOptionPane.showConfirmDialog(null,"silinsin","silme islemi",JOptionPane.YES_NO_OPTION);
        if(delete==JOptionPane.YES_OPTION){
                  pat=baglan.prepareStatement("DELETE FROM emlakislem WHERE id=?");
                  pat.setInt(1, id);
               
                  pat.execute();
                  tabloemlakislem();
                      tx_kiralik_isletme_fiyat.setText("");
               tx_kira_süresi.setText("");
               tx_kira_baslangic_t.setText("");
                 tx_kira_bitis_t.setText(""); 
                 tx_satis_t.setText("");
                tx_emlak_id.setText("");
                
                  
                
        } 
              } catch (SQLException ex) {
                  Logger.getLogger(yontoyuncuekleme.class.getName()).log(Level.SEVERE, null, ex);
              }
    }//GEN-LAST:event_jBdeleteActionPerformed

    private void tx_kira_bitis_tActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tx_kira_bitis_tActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tx_kira_bitis_tActionPerformed

    private void tx_satis_tActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tx_satis_tActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tx_satis_tActionPerformed

    private void tx_soyadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tx_soyadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tx_soyadActionPerformed

    private void jBoyunculisteleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBoyunculisteleActionPerformed
        // TODO add your handling code here:
             try {
            // TODO add your handling code here:
            String oyuncuid=txtoid.getSelectedItem().toString();
            pat=baglan.prepareStatement("SELECT*FROM oyuncu WHERE id=?");
            pat.setString(1, oyuncuid);
            
            rs=pat.executeQuery();
            if(rs.next()==true){
                tx_ad.setText(rs.getString(2));
                tx_soyad.setText(rs.getString(3));
                tx_kullaniciAdi.setText(rs.getString(4));
                 tx_sifre.setText(rs.getString(5));
                 tx_yemekMik.setText(rs.getString(6));
                  tx_esyaMik.setText(rs.getString(7));
                   tx_paraMik.setText(rs.getString(8));
                         tx_calisma_bas_t.setText(rs.getString(9));
                 tx_calisma_bit_t.setText(rs.getString(10));
                 tx_calisma_s.setText(rs.getString(11));
                tx_calisma_gun_s.setText(rs.getString(12));
                tx_gunluk_k_para.setText(rs.getString(13));
                  
              
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(yontoyuncuekleme.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jBoyunculisteleActionPerformed

    private void jBemlakaraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBemlakaraActionPerformed
      try{
            String marketid=txteid.getSelectedItem().toString();
            pat=baglan.prepareStatement("SELECT*FROM emlak WHERE id=?");
            pat.setString(1, marketid);
            
            rs=pat.executeQuery();
          
            if(rs.next()==true){
               tx_emlak_komisyonu.setText(rs.getString(2));
                tx_g_para_gideri.setText(rs.getString(3));
               tx_isletme_id.setText(rs.getString(4));
                
                 
                 
              
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(yontoyuncuekleme.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jBemlakaraActionPerformed

    private void tx_kazancActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tx_kazancActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tx_kazancActionPerformed

    private void tx_calisma_gun_sActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tx_calisma_gun_sActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tx_calisma_gun_sActionPerformed

    private void tx_gunluk_k_paraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tx_gunluk_k_paraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tx_gunluk_k_paraActionPerformed

    private void tx_calisma_bas_tActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tx_calisma_bas_tActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tx_calisma_bas_tActionPerformed

public void delete(){
    //oyuncu tablosuna gore düzenle
        // DefaultTableModel RecordTable=(DefaultTableModel)jTable1.getModel();
        //int satirSec=jTable1.getSelectedRow();
     
       
              try {
             //int id=Integer.parseInt(RecordTable.getValueAt(satirSec, 0).toString());
               int id= Integer.parseInt(txtoid.getSelectedItem().toString());
       int delete=JOptionPane.showConfirmDialog(null,"silinsin","silme islemi",JOptionPane.YES_NO_OPTION);
        if(delete==JOptionPane.YES_OPTION){
                  pat=baglan.prepareStatement("DELETE FROM oyuncu WHERE id=?");
                  pat.setInt(1, id);
                  pat.execute();
                  //tablocalisanoyuncu();
                  tx_ad.setText("");
                  tx_ad.requestFocus();
                  tx_soyad.setText("");
                  tx_kullaniciAdi.setText("");
                  tx_sifre.setText("");
                   tx_yemekMik.setText("");
                tx_esyaMik.setText("");
                tx_paraMik.setText("");
                     tx_calisma_bas_t.setText("");
                   tx_calisma_bit_t.setText("");
                    tx_calisma_s.setText("");
                     tx_calisma_gun_s.setText("");
                      tx_gunluk_k_para.setText("");
                  
                
        } 
              } catch (SQLException ex) {
                  Logger.getLogger(yontoyuncuekleme.class.getName()).log(Level.SEVERE, null, ex);
              }
}
    private void jBhesaplaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBhesaplaActionPerformed
        // TODO add your handling code here:
               Date gunbit=new Date();
      SimpleDateFormat f=new SimpleDateFormat("yyyy-MM-dd");
       Date gunbas=new Date();
      SimpleDateFormat f1=new SimpleDateFormat("yyyy-MM-dd");
        try {
            gunbit=f.parse(tx_calisma_bit_t.getText());
             gunbas=f1.parse(tx_calisma_bas_t.getText());
            
            
        } catch (ParseException ex) {
            Logger.getLogger(marketcalisma.class.getName()).log(Level.SEVERE, null, ex);
        }
        Long tarihfarki=(gunbit.getTime()-gunbas.getTime())/(1000*60*60*24);
        System.out.println("tarihfark."+tarihfarki);
          if(tarihfarki>0){
         int yeniEsyaM=Integer.parseInt(tx_esyaMik.getText());
         yeniEsyaM=(int) (yeniEsyaM-tarihfarki);
          String yeniEsyaMik =Integer.toString(yeniEsyaM);
          if(yeniEsyaM==0){
              delete();
          }
          
          int yeniyemekM=Integer.parseInt(tx_yemekMik.getText());
         yeniyemekM=(int) (yeniyemekM-tarihfarki);
          String yeniYemekMik =Integer.toString(yeniyemekM);
          if(yeniyemekM==0){
              delete();
          }
          
          try {
                  String ad=tx_ad.getText();
            String soyad=tx_soyad.getText();
            String kullaniciAdi=tx_kullaniciAdi.getText();
            String sifre=String.valueOf(tx_sifre.getText());
           // String yemekMik=tx_yemekMik.getText();
           // String esyaMik=tx_esyaMik.getText();
            String paraMik=tx_paraMik.getText();
            
      String calisma_bas_t=tx_calisma_bas_t.getText();
       String calisma_bit_t=tx_calisma_bit_t.getText();
             String calisma_s=tx_calisma_s.getText();
             String calisma_gun_s = tx_calisma_gun_s.getText();
            String gunluk_k_para= tx_gunluk_k_para.getText();
            
            String oyuncuid=txtoid.getSelectedItem().toString();
             pat=baglan.prepareStatement("UPDATE oyuncu SET oyuncuAd=?,oyuncuSoyad=?,kullaniciAdi=?,sifre=?,yemekMik=?,esyaMik=?,paraMik=?,calisma_bas_t=?,calisma_bitis_t=?,calisma_saat=?,calisma_gün_s=?,gunluk_k_para=? WHERE id=?");
              
               pat.setString(1, ad);
            pat.setString(2, soyad);
            pat.setString(3, kullaniciAdi);
            pat.setString(4,sifre);
             pat.setString(5,yeniYemekMik );
            pat.setString(6,yeniEsyaMik );
            pat.setString(7,paraMik);
             pat.setString(8,calisma_bas_t);
              pat.setString(9,calisma_bit_t);
               pat.setString(10,calisma_s);
                pat.setString(11,calisma_gun_s );
                pat.setString(12,gunluk_k_para );
                pat.setString(13,oyuncuid);
                
                int k=pat.executeUpdate();
                 // tablocalisanoyuncu();
             int gunluk_kazanc= Integer.parseInt(tx_gunluk_k_para.getText());
           int tutar=(int) (tarihfarki*gunluk_kazanc);
             // System.out.println("fmfdm"+tutar);
            String kazanc= String.valueOf(tutar);
            tx_kazanc.setText(kazanc);
            if(k==1){
                JOptionPane.showMessageDialog(this, "veri tabani eklemesi basarili");
               
                /*tx_ad.setText("");
                tx_soyad.setText("");
                tx_kullaniciAdi.setText("");
                tx_sifre.setText("");
                tx_yemekMik.setText("");
                tx_esyaMik.setText("");
                tx_paraMik.setText("");
                  tx_calisma_bas_t.setText("");
                   tx_calisma_bit_t.setText("");
                    tx_calisma_s.setText("");
                     tx_calisma_gun_s.setText("");
                      tx_gunluk_k_para.setText("");
                      tx_ad.requestFocus();
               idoyuncu();*/
            }
          
          
           
              
          } catch (SQLException ex) {
              Logger.getLogger(marketcalisma.class.getName()).log(Level.SEVERE, null, ex);
          }
         
      }
    }//GEN-LAST:event_jBhesaplaActionPerformed


    private void jBkiralamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBkiralamaActionPerformed
        // TODO add your handling code here:
            Date gunbit=new Date();
      SimpleDateFormat f=new SimpleDateFormat("yyyy-MM-dd");
       Date gunbas=new Date();
      SimpleDateFormat f1=new SimpleDateFormat("yyyy-MM-dd");
        try {
            gunbit=f.parse(tx_kira_bitis_t.getText());
             gunbas=f1.parse(tx_kira_baslangic_t.getText());
            
            
        } catch (ParseException ex) {
            Logger.getLogger(marketcalisma.class.getName()).log(Level.SEVERE, null, ex);
        }
          Long tarihfarki=(gunbit.getTime()-gunbas.getTime())/(1000*60*60*24);
       // System.out.println("tarihfark."+tarihfarki);
         
         int tkazanc =Integer.parseInt( tx_kazanc.getText());
         int kiralik_isletme_fiyati=Integer.parseInt(tx_kiralik_isletme_fiyat.getText());
         int kira_ucreti=(int) (kiralik_isletme_fiyati*tarihfarki);
       String kira_ucreti2 =Integer.toString(kira_ucreti);
         tx_kira_ucreti.setText(kira_ucreti2);
          int komisyon_ucret=Integer.parseInt( tx_emlak_komisyonu.getText());
          int toplam_kira_ucreti=(kira_ucreti+komisyon_ucret);
           String toplam_kira_ucreti1 =Integer.toString(toplam_kira_ucreti);
           tx_toplamkira_ucreti.setText(toplam_kira_ucreti1);
         
          int yenitutar=(int) (tkazanc-toplam_kira_ucreti);
          String kalanpara= String.valueOf(yenitutar);
            tx_kazanc.setText(kalanpara);
    }//GEN-LAST:event_jBkiralamaActionPerformed

    private void jBtemizleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtemizleActionPerformed
        // TODO add your handling code here:
        veriTemizle();
    }//GEN-LAST:event_jBtemizleActionPerformed

    private void jButoyuncutablActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButoyuncutablActionPerformed
        // TODO add your handling code here:
        new tablooyuncu().setVisible(true);
    }//GEN-LAST:event_jButoyuncutablActionPerformed

    private void jBcıkısActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBcıkısActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jBcıkısActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(emlakislem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(emlakislem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(emlakislem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(emlakislem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new emlakislem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBanlasma;
    private javax.swing.JButton jBara;
    private javax.swing.JButton jBcıkıs;
    private javax.swing.JButton jBdelete;
    private javax.swing.JButton jBekle;
    private javax.swing.JButton jBemlakara;
    private javax.swing.JButton jBhesapla;
    private javax.swing.JButton jBkiralama;
    private javax.swing.JButton jBoyunculistele;
    private javax.swing.JButton jBtemizle;
    private javax.swing.JButton jButoyuncutabl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTemlakislem;
    private javax.swing.JTextField tx_ad;
    private javax.swing.JTextField tx_calisma_bas_t;
    private javax.swing.JTextField tx_calisma_bit_t;
    private javax.swing.JTextField tx_calisma_gun_s;
    private javax.swing.JTextField tx_calisma_s;
    private javax.swing.JTextField tx_emlak_id;
    private javax.swing.JTextField tx_emlak_komisyonu;
    private javax.swing.JTextField tx_esyaMik;
    private javax.swing.JTextField tx_g_para_gideri;
    private javax.swing.JTextField tx_gunluk_k_para;
    private javax.swing.JTextField tx_isletme_id;
    private javax.swing.JTextField tx_kazanc;
    private javax.swing.JTextField tx_kira_baslangic_t;
    private javax.swing.JTextField tx_kira_bitis_t;
    private javax.swing.JTextField tx_kira_süresi;
    private javax.swing.JTextField tx_kira_ucreti;
    private javax.swing.JTextField tx_kiralik_isletme_fiyat;
    private javax.swing.JTextField tx_kullaniciAdi;
    private javax.swing.JTextField tx_paraMik;
    private javax.swing.JTextField tx_satis_t;
    private javax.swing.JTextField tx_sifre;
    private javax.swing.JTextField tx_soyad;
    private javax.swing.JTextField tx_toplamkira_ucreti;
    private javax.swing.JTextField tx_yemekMik;
    private javax.swing.JComboBox<String> txteid;
    private javax.swing.JComboBox<String> txteiid;
    private javax.swing.JComboBox<String> txtoid;
    // End of variables declaration//GEN-END:variables
}
