
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Aylin
 */
public class isletme extends javax.swing.JFrame {

    /**
     * Creates new form isletme
     */
    public isletme() {
        initComponents();
        connection();
        idisletme();
        tablo();
        
      
    }
      Connection baglan; 
  PreparedStatement pat;
  ResultSet rs;
  int q,i;
   
   public void connection(){
       try{
       Class.forName("com.mysql.jdbc.Driver");
     String bag="jdbc:mysql://localhost:3306/new_proje";
     String username="root";
     String sifre="684217";
     baglan= DriverManager.getConnection(bag,username,sifre);
    JOptionPane.showMessageDialog(null, "veri tabani baglantisi basarili");
   
       }
       catch (ClassNotFoundException ex) {
            Logger.getLogger(yontoyuncuekleme.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(yontoyuncuekleme.class.getName()).log(Level.SEVERE, null, ex);
        }
       
   }
     public void tablo(){
        try {
            pat=baglan.prepareStatement("SELECT*FROM isletme");
 
              rs=pat.executeQuery();
            ResultSetMetaData stveri=rs.getMetaData();
            q=stveri.getColumnCount();
            DefaultTableModel RecordTable=(DefaultTableModel)jTablo.getModel();
                    RecordTable.setRowCount(0);
             while(rs.next()){
                 Vector sutunVeri=new Vector();
                 for(i =1;i<=q;i++){
                     sutunVeri.add(rs.getString("id"));
                     sutunVeri.add(rs.getString("isletmeSeviyesi"));
                     sutunVeri.add(rs.getString("isletmeFiyati"));
                     sutunVeri.add(rs.getString("isletmeBasTarihi"));
                     sutunVeri.add(rs.getString("SbtGelirOrani"));
                      sutunVeri.add(rs.getString("sbtGelirMiktari"));
                      sutunVeri.add(rs.getString("yöneticİsletmeÜcreti"));
                      sutunVeri.add(rs.getString("oyuncuİsletmeÜcreti"));
                      sutunVeri.add(rs.getString("isletmeKapasitesi"));
                      sutunVeri.add(rs.getString("oyuncu_id"));
                      sutunVeri.add(rs.getString("yonetici_id"));
                 }
                 RecordTable.addRow(sutunVeri);
                 
             }       
            
            
        } catch (SQLException ex) {
            Logger.getLogger(yontoyuncuekleme.class.getName()).log(Level.SEVERE, null, ex);
        }
      }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTablo = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tx_isletmeSeviyesi = new javax.swing.JTextField();
        tx_isletmeFiyati = new javax.swing.JTextField();
        tx_SbtGelirOrani = new javax.swing.JTextField();
        tx_sbtGelirMiktari = new javax.swing.JTextField();
        tx_yöneticiİsletmeÜcreti = new javax.swing.JTextField();
        tx_oyuncuİsletmeÜcreti = new javax.swing.JTextField();
        tx_isletmeKapasitesi = new javax.swing.JTextField();
        tx_oyuncu_id = new javax.swing.JTextField();
        jBekle = new javax.swing.JButton();
        jBgüncelle = new javax.swing.JButton();
        jBdelete = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txtiid = new javax.swing.JComboBox<>();
        jBarama = new javax.swing.JButton();
        tx_tarih = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        tx_yonetici_id = new javax.swing.JTextField();
        jBcıkıs = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTablo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "id", "isletmeSeviyesi", "isletmeFiyati", "isletmaBasTarihi", "SbtGelirOrani", "sbtGelirMiktari", "yöneticiİsletmeÜcreti", "oyuncuİsletmeÜcreti", "isletmeKapasitesi", "oyuncu_id", "yonetici_id"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTablo);

        jLabel1.setText("isletme seviyesi:");

        jLabel2.setText("isletmeFiyati:");

        jLabel3.setText("isletmeBasTarihi:");

        jLabel4.setText("SbtGelirOrani:");

        jLabel5.setText("sbtGelirMiktari:");

        jLabel6.setText("yöneticiİsletmeÜcreti:");

        jLabel7.setText("oyuncuİsletmeÜcreti:");

        jLabel8.setText("isletmeKapasitesi:");

        jLabel9.setText("oyuncu_id:");

        tx_oyuncuİsletmeÜcreti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tx_oyuncuİsletmeÜcretiActionPerformed(evt);
            }
        });

        tx_isletmeKapasitesi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tx_isletmeKapasitesiActionPerformed(evt);
            }
        });

        tx_oyuncu_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tx_oyuncu_idActionPerformed(evt);
            }
        });

        jBekle.setText("EKLE");
        jBekle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBekleActionPerformed(evt);
            }
        });

        jBgüncelle.setText("GÜNCELLE");
        jBgüncelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBgüncelleActionPerformed(evt);
            }
        });

        jBdelete.setText("DELETE");
        jBdelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBdeleteActionPerformed(evt);
            }
        });

        jLabel10.setText("isletme_id");

        txtiid.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jBarama.setText("ARAMA");
        jBarama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBaramaActionPerformed(evt);
            }
        });

        jLabel11.setText("yönetici_id:");

        jBcıkıs.setText("cıkıs");
        jBcıkıs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBcıkısActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(62, 62, 62)
                                        .addComponent(jLabel1)
                                        .addGap(18, 18, 18)
                                        .addComponent(tx_isletmeSeviyesi, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(59, 59, 59)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(tx_SbtGelirOrani, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(tx_sbtGelirMiktari, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel2))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(tx_isletmeFiyati, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(tx_tarih, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tx_isletmeKapasitesi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tx_oyuncu_id, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tx_yöneticiİsletmeÜcreti, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(18, 18, 18)
                                        .addComponent(tx_oyuncuİsletmeÜcreti, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(tx_yonetici_id, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(144, 144, 144)
                                .addComponent(jLabel10)
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jBarama)
                                    .addComponent(txtiid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(86, 86, 86)
                                .addComponent(jBekle)
                                .addGap(44, 44, 44)
                                .addComponent(jBgüncelle)
                                .addGap(50, 50, 50)
                                .addComponent(jBdelete)
                                .addGap(53, 53, 53)
                                .addComponent(jBcıkıs)))
                        .addGap(0, 283, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel6)
                    .addComponent(tx_isletmeSeviyesi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tx_yöneticiİsletmeÜcreti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(txtiid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tx_isletmeFiyati, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(tx_oyuncuİsletmeÜcreti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBarama))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tx_isletmeKapasitesi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(tx_tarih, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(tx_SbtGelirOrani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(tx_sbtGelirMiktari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(tx_oyuncu_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(tx_yonetici_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBekle)
                    .addComponent(jBgüncelle)
                    .addComponent(jBdelete)
                    .addComponent(jBcıkıs))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tx_oyuncuİsletmeÜcretiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tx_oyuncuİsletmeÜcretiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tx_oyuncuİsletmeÜcretiActionPerformed

    private void tx_isletmeKapasitesiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tx_isletmeKapasitesiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tx_isletmeKapasitesiActionPerformed

    private void tx_oyuncu_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tx_oyuncu_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tx_oyuncu_idActionPerformed

    private void jBekleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBekleActionPerformed
        // TODO add your handling code here:
          try {
            // TODO add your handling code here:
           
            String isletmeSeviyesi=tx_isletmeSeviyesi.getText();
            String isletmeFiyati=tx_isletmeFiyati.getText();
            
            /*SimpleDateFormat dateformat=new SimpleDateFormat("yyyy-MM-dd");
            String isletmeBasTarihi=dateformat.format(jDate1.getDate());*/
            
            String isletmeBasTarihi=tx_tarih.getText();
            String SbtGelirOrani=tx_SbtGelirOrani.getText();
            String sbtGelirMiktari=tx_sbtGelirMiktari.getText();
            String yöneticiİsletmeÜcreti=tx_yöneticiİsletmeÜcreti.getText();
            String oyuncuİsletmeÜcreti=tx_oyuncuİsletmeÜcreti.getText();
            String isletmeKapasitesi=tx_isletmeKapasitesi.getText();
            String oyuncu_id=tx_oyuncu_id.getText();
            String yonetici_id=tx_yonetici_id.getText();
           
            
            pat=baglan.prepareStatement("INSERT INTO isletme(isletmeSeviyesi,isletmeFiyati,isletmeBasTarihi,SbtGelirOrani,sbtGelirMiktari,yöneticİsletmeÜcreti,oyuncuİsletmeÜcreti,isletmeKapasitesi,oyuncu_id,yonetici_id) VALUES(?,?,?,?,?,?,?,?,?,?)");
            pat.setString(1,isletmeSeviyesi);
            pat.setString(2, isletmeFiyati);
            pat.setString(3, isletmeBasTarihi);
            pat.setString(4,SbtGelirOrani);
            pat.setString(5,sbtGelirMiktari);
             pat.setString(6,yöneticiİsletmeÜcreti);
              pat.setString(7,oyuncuİsletmeÜcreti);
               pat.setString(8,isletmeKapasitesi); 
               pat.setString(9,oyuncu_id);
                pat.setString(10,yonetici_id);
               
            int k=pat.executeUpdate();
             tablo();
            if(k==1){
                JOptionPane.showMessageDialog(this, "veri tabani eklemesi basarili");
                tx_isletmeSeviyesi.setText("");
                tx_isletmeFiyati.setText("");
                tx_isletmeFiyati.setText("");
                //jDate1.setDateFormatString("");
                 tx_tarih.setText("");
                tx_SbtGelirOrani.setText("");
                tx_sbtGelirMiktari.setText("");
                tx_yöneticiİsletmeÜcreti.setText("");
                tx_oyuncuİsletmeÜcreti.setText("");
                tx_isletmeKapasitesi.setText("");
                tx_oyuncu_id.setText("");                
                  tx_yonetici_id.setText("");                                                               
                                                                             
                  
            }
            else{
                JOptionPane.showMessageDialog(this, "veri tabani eklemesi basarisiz");
            }
               
        } catch (SQLException ex) {
            Logger.getLogger(yontoyuncuekleme.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jBekleActionPerformed

    private void jBaramaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBaramaActionPerformed
        // TODO add your handling code here:
            try {
            // TODO add your handling code here:
            String isletmeid=txtiid.getSelectedItem().toString();
            pat=baglan.prepareStatement("SELECT*FROM isletme WHERE id=?");
            pat.setString(1, isletmeid);
            
            rs=pat.executeQuery();
          
            if(rs.next()==true){
               tx_isletmeSeviyesi.setText(rs.getString(2));
                tx_isletmeFiyati.setText(rs.getString(3));
               //jDate1.setDateFormatString(rs.getString(4));
               tx_tarih.setText(rs.getString(4));
                 tx_SbtGelirOrani.setText(rs.getString(5));
                  tx_sbtGelirMiktari.setText(rs.getString(6));
                   tx_yöneticiİsletmeÜcreti.setText(rs.getString(7));
                    tx_oyuncuİsletmeÜcreti.setText(rs.getString(8));
                     tx_isletmeKapasitesi.setText(rs.getString(9));
                      tx_oyuncu_id.setText(rs.getString(10));
                 tx_yonetici_id.setText(rs.getString(11));
                 
              
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(yontoyuncuekleme.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jBaramaActionPerformed

    private void jBgüncelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBgüncelleActionPerformed
        // TODO add your handling code here:
            try {
            // TODO add your handling code here:
       String isletmeSeviyesi=tx_isletmeSeviyesi.getText();
            String isletmeFiyati=tx_isletmeFiyati.getText();
           /* SimpleDateFormat dateformat=new SimpleDateFormat("yyyy-MM-dd");
            String isletmeBasTarihi=dateformat.format(jDate1.getDate());*/
             String isletmeBasTarihi=tx_tarih.getText();
            String SbtGelirOrani=tx_SbtGelirOrani.getText();
            String sbtGelirMiktari=tx_sbtGelirMiktari.getText();
            String yöneticiİsletmeÜcreti=tx_yöneticiİsletmeÜcreti.getText();
            String oyuncuİsletmeÜcreti=tx_oyuncuİsletmeÜcreti.getText();
            String isletmeKapasitesi=tx_isletmeKapasitesi.getText();
            String oyuncu_id=tx_oyuncu_id.getText();
            String yonetici_id=tx_yonetici_id.getText();
            
            String isletmeid=txtiid.getSelectedItem().toString();
             pat=baglan.prepareStatement("UPDATE isletme SET isletmeSeviyesi=?,isletmeFiyati=?,isletmeBasTarihi=?,SbtGelirOrani=?,sbtGelirMiktari=?,yöneticİsletmeÜcreti=?,oyuncuİsletmeÜcreti=?,isletmeKapasitesi=?,oyuncu_id=?,yonetici_id=? WHERE id=?");
             pat.setString(1,isletmeSeviyesi);
            pat.setString(2, isletmeFiyati);
            pat.setString(3, isletmeBasTarihi);
            pat.setString(4,SbtGelirOrani);
            pat.setString(5,sbtGelirMiktari);
             pat.setString(6,yöneticiİsletmeÜcreti);
              pat.setString(7,oyuncuİsletmeÜcreti);
               pat.setString(8,isletmeKapasitesi); 
               pat.setString(9,oyuncu_id);
               pat.setString(10,yonetici_id);
            pat.setString(11,isletmeid);
            
              int k=pat.executeUpdate();
            if(k==1){
              JOptionPane.showMessageDialog(this, "kayit basariyla guncellendi");
           tablo();
                 tx_isletmeSeviyesi.setText("");
                tx_isletmeFiyati.setText("");
                tx_isletmeFiyati.setText("");
               // jDate1.setDateFormatString("");
               tx_tarih.setText("");
                tx_SbtGelirOrani.setText("");
                tx_sbtGelirMiktari.setText("");
                tx_yöneticiİsletmeÜcreti.setText("");
                tx_oyuncuİsletmeÜcreti.setText("");
                tx_isletmeKapasitesi.setText("");
                tx_oyuncu_id.setText("");   
            tx_yonetici_id.setText("");
                  tx_isletmeSeviyesi.requestFocus();
                idisletme();
                
                  
            }
        } catch (SQLException ex) {
            Logger.getLogger(yontoyuncuekleme.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jBgüncelleActionPerformed

    private void jBdeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBdeleteActionPerformed
        // TODO add your handling code here:
              DefaultTableModel RecordTable=(DefaultTableModel)jTablo.getModel();
        int satirSec=jTablo.getSelectedRow();
      
      
              try {
             int id=Integer.parseInt(RecordTable.getValueAt(satirSec, 0).toString());
       int delete=JOptionPane.showConfirmDialog(null,"silinsin","silme islemi",JOptionPane.YES_NO_OPTION);
        if(delete==JOptionPane.YES_OPTION){
                  pat=baglan.prepareStatement("DELETE FROM isletme WHERE id=?");
                  pat.setInt(1, id);
                  pat.execute();
                  tablo();
                    tx_isletmeSeviyesi.setText("");
                tx_isletmeFiyati.setText("");
                tx_isletmeFiyati.setText("");
                //jDate1.setDateFormatString("");
                tx_tarih.setText("");
                tx_SbtGelirOrani.setText("");
                tx_sbtGelirMiktari.setText("");
                tx_yöneticiİsletmeÜcreti.setText("");
                tx_oyuncuİsletmeÜcreti.setText("");
                tx_isletmeKapasitesi.setText("");
                tx_oyuncu_id.setText("");  
                 tx_yonetici_id.setText(""); 
                  
                
        } 
              } catch (SQLException ex) {
                  Logger.getLogger(yontoyuncuekleme.class.getName()).log(Level.SEVERE, null, ex);
              }
    }//GEN-LAST:event_jBdeleteActionPerformed

    private void jBcıkısActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBcıkısActionPerformed
        // TODO add your handling code here
        this.setVisible(false);
    }//GEN-LAST:event_jBcıkısActionPerformed

              
   public void idisletme() {
        try {
            pat=baglan.prepareStatement("SELECT id FROM isletme");
            rs=pat.executeQuery();
            txtiid.removeAllItems();
            while(rs.next()){
                txtiid.addItem(rs.getString(1));
            }
        } catch (SQLException ex) {
            Logger.getLogger(yontoyuncuekleme.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(isletme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(isletme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(isletme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(isletme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new isletme().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBarama;
    private javax.swing.JButton jBcıkıs;
    private javax.swing.JButton jBdelete;
    private javax.swing.JButton jBekle;
    private javax.swing.JButton jBgüncelle;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTablo;
    private javax.swing.JTextField tx_SbtGelirOrani;
    private javax.swing.JTextField tx_isletmeFiyati;
    private javax.swing.JTextField tx_isletmeKapasitesi;
    private javax.swing.JTextField tx_isletmeSeviyesi;
    private javax.swing.JTextField tx_oyuncu_id;
    private javax.swing.JTextField tx_oyuncuİsletmeÜcreti;
    private javax.swing.JTextField tx_sbtGelirMiktari;
    private javax.swing.JTextField tx_tarih;
    private javax.swing.JTextField tx_yonetici_id;
    private javax.swing.JTextField tx_yöneticiİsletmeÜcreti;
    private javax.swing.JComboBox<String> txtiid;
    // End of variables declaration//GEN-END:variables
}
