
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Aylin
 */
public class magaza extends javax.swing.JFrame {

    /**
     * Creates new form magaza
     */
    public magaza() {
        initComponents();
        connection();
        idmagaza();
        tablomagaza();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jTMagaza = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tx_esya_ucreti = new javax.swing.JTextField();
        tx_g_esya_gideri = new javax.swing.JTextField();
        tx_isletme_id = new javax.swing.JTextField();
        jBekle = new javax.swing.JButton();
        jBgüncelle = new javax.swing.JButton();
        jBdelete = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtmağid = new javax.swing.JComboBox<>();
        jBara = new javax.swing.JButton();
        jBcıkıs = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTMagaza.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "id", "esya_ucreti", "g_esya_gideri", "isletme_id"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTMagaza);

        jLabel1.setText("esya_ucreti:");

        jLabel2.setText("g_esya_gideri:");

        jLabel3.setText("isletme_id:");

        tx_g_esya_gideri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tx_g_esya_gideriActionPerformed(evt);
            }
        });

        jBekle.setText("EKLE");
        jBekle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBekleActionPerformed(evt);
            }
        });

        jBgüncelle.setText("GÜNCELLE");
        jBgüncelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBgüncelleActionPerformed(evt);
            }
        });

        jBdelete.setText("DELETE");
        jBdelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBdeleteActionPerformed(evt);
            }
        });

        jLabel4.setText("magaza id:");

        txtmağid.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jBara.setText("ARA");
        jBara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBaraActionPerformed(evt);
            }
        });

        jBcıkıs.setText("cıkıs");
        jBcıkıs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBcıkısActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 721, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(tx_isletme_id, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(26, 26, 26)
                                        .addComponent(txtmağid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jBara, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(85, 85, 85))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tx_g_esya_gideri, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(tx_esya_ucreti, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(168, 168, 168)
                                        .addComponent(jBekle)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jBgüncelle)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jBdelete)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jBcıkıs)))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tx_esya_ucreti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBekle)
                        .addComponent(jBgüncelle)
                        .addComponent(jBdelete)
                        .addComponent(jBcıkıs)))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(tx_g_esya_gideri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(tx_isletme_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtmağid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBara)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tx_g_esya_gideriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tx_g_esya_gideriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tx_g_esya_gideriActionPerformed

    private void jBgüncelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBgüncelleActionPerformed
        // TODO add your handling code here:
                try {
            // TODO add your handling code here:
      String esya_ucreti=tx_esya_ucreti.getText();
            String g_esya_gideri=tx_g_esya_gideri.getText();
            String isletme_id=tx_isletme_id.getText();
            
            String magazaid=txtmağid.getSelectedItem().toString();
            pat=baglan.prepareStatement("UPDATE magaza SET esya_ucreti=?,g_esya_gideri=?,isletme_id=? WHERE id=?");
           pat.setString(1,esya_ucreti);
            pat.setString(2, g_esya_gideri);
            pat.setString(3, isletme_id);
            pat.setString(4,magazaid);
            
              int k=pat.executeUpdate();
            if(k==1){
              JOptionPane.showMessageDialog(this, "kayit basariyla guncellendi");
           tablomagaza();
               
                   tx_esya_ucreti.setText("");
                tx_g_esya_gideri.setText("");
                tx_isletme_id.setText("");
                 tx_esya_ucreti.requestFocus();
                idmagaza();
                
                  
            }
        } catch (SQLException ex) {
            Logger.getLogger(yontoyuncuekleme.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jBgüncelleActionPerformed

    private void jBaraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBaraActionPerformed
        // TODO add your handling code here:
           try {
            // TODO add your handling code here:
            String marketid=txtmağid.getSelectedItem().toString();
            pat=baglan.prepareStatement("SELECT*FROM magaza WHERE id=?");
            pat.setString(1, marketid);
            
            rs=pat.executeQuery();
          
            if(rs.next()==true){
               tx_esya_ucreti.setText(rs.getString(2));
                tx_g_esya_gideri.setText(rs.getString(3));
               tx_isletme_id.setText(rs.getString(4));
                
                 
                 
              
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(yontoyuncuekleme.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jBaraActionPerformed

    private void jBekleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBekleActionPerformed
        // TODO add your handling code here:
         try {
            // TODO add your handling code here:
            String esya_ucreti=tx_esya_ucreti.getText();
            String g_esya_gideri=tx_g_esya_gideri.getText();
            String isletme_id=tx_isletme_id.getText();
   
           
        
            
           
            
            pat=baglan.prepareStatement("INSERT INTO magaza(esya_ucreti,g_esya_gideri,isletme_id) VALUES(?,?,?)");
            pat.setString(1,esya_ucreti);
            pat.setString(2, g_esya_gideri);
            pat.setString(3, isletme_id);
            
           
            int k=pat.executeUpdate();
             tablomagaza();
            if(k==1){
                JOptionPane.showMessageDialog(this, "veri tabani eklemesi basarili");
               
                tx_esya_ucreti.setText("");
                tx_g_esya_gideri.setText("");
                tx_isletme_id.setText("");
             
             
                  
            }
            else{
                JOptionPane.showMessageDialog(this, "veri tabani eklemesi basarisiz");
            }
               
        } catch (SQLException ex) {
            Logger.getLogger(yontoyuncuekleme.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jBekleActionPerformed

    private void jBdeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBdeleteActionPerformed
        // TODO add your handling code here:
              DefaultTableModel RecordTable=(DefaultTableModel)jTMagaza.getModel();
        int satirSec=jTMagaza.getSelectedRow();
      
      
              try {
             int id=Integer.parseInt(RecordTable.getValueAt(satirSec, 0).toString());
       int delete=JOptionPane.showConfirmDialog(null,"silinsin","silme islemi",JOptionPane.YES_NO_OPTION);
        if(delete==JOptionPane.YES_OPTION){
                  pat=baglan.prepareStatement("DELETE FROM magaza WHERE id=?");
                  pat.setInt(1, id);
                  pat.execute();
                  tablomagaza();
                   tx_esya_ucreti.setText("");
                tx_g_esya_gideri.setText("");
                tx_isletme_id.setText("");
                
                  
                
        } 
              } catch (SQLException ex) {
                  Logger.getLogger(yontoyuncuekleme.class.getName()).log(Level.SEVERE, null, ex);
              }
    }//GEN-LAST:event_jBdeleteActionPerformed

    private void jBcıkısActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBcıkısActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jBcıkısActionPerformed
  Connection baglan; 
  PreparedStatement pat;
  ResultSet rs;
  int q,i;
   
   public void connection(){
       try{
       Class.forName("com.mysql.jdbc.Driver");
     String bag="jdbc:mysql://localhost:3306/new_proje";
     String username="root";
     String sifre="684217";
     baglan= DriverManager.getConnection(bag,username,sifre);
    JOptionPane.showMessageDialog(null, "veri tabani baglantisi basarili");
   
       }
       catch (ClassNotFoundException ex) {
            Logger.getLogger(yontoyuncuekleme.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(yontoyuncuekleme.class.getName()).log(Level.SEVERE, null, ex);
        }
       
   }
                  public void tablomagaza(){
        try {
            pat=baglan.prepareStatement("SELECT*FROM magaza");
 
              rs=pat.executeQuery();
            ResultSetMetaData stveri=rs.getMetaData();
            q=stveri.getColumnCount();
            DefaultTableModel RecordTable=(DefaultTableModel)jTMagaza.getModel();
                    RecordTable.setRowCount(0);
             while(rs.next()){
                 Vector sutunVeri=new Vector();
                 for(i =1;i<=q;i++){
                     sutunVeri.add(rs.getString("id"));
                     sutunVeri.add(rs.getString("esya_ucreti"));
                     sutunVeri.add(rs.getString("g_esya_gideri"));
                     sutunVeri.add(rs.getString("isletme_id"));
                   
                 }
                 RecordTable.addRow(sutunVeri);
                 
             }       
            
            
        } catch (SQLException ex) {
            Logger.getLogger(yontoyuncuekleme.class.getName()).log(Level.SEVERE, null, ex);
        }
      }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(magaza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(magaza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(magaza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(magaza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new magaza().setVisible(true);
            }
        });
    }
public void idmagaza() {
        try {
            pat=baglan.prepareStatement("SELECT id FROM magaza");
            rs=pat.executeQuery();
            txtmağid.removeAllItems();
            while(rs.next()){
                txtmağid.addItem(rs.getString(1));
            }
        } catch (SQLException ex) {
            Logger.getLogger(yontoyuncuekleme.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBara;
    private javax.swing.JButton jBcıkıs;
    private javax.swing.JButton jBdelete;
    private javax.swing.JButton jBekle;
    private javax.swing.JButton jBgüncelle;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTMagaza;
    private javax.swing.JTextField tx_esya_ucreti;
    private javax.swing.JTextField tx_g_esya_gideri;
    private javax.swing.JTextField tx_isletme_id;
    private javax.swing.JComboBox<String> txtmağid;
    // End of variables declaration//GEN-END:variables
}
