
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Aylin
 */
public class magazacalisma extends javax.swing.JFrame {

    /**
     * Creates new form magazacalisma
     */
    public magazacalisma() {
        initComponents();
         connection();
        tablocalisanoyuncu();
        idoyuncu();
        idmagaza();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
           Connection baglan; 
  PreparedStatement pat;
  ResultSet rs;
  int q,i;
   
   public void connection(){
       try{
       Class.forName("com.mysql.jdbc.Driver");
     String bag="jdbc:mysql://localhost:3306/new_proje";
     String username="root";
     String sifre="684217";
     baglan= DriverManager.getConnection(bag,username,sifre);
    JOptionPane.showMessageDialog(null, "veri tabani baglantisi basarili");
   
       }
       catch (ClassNotFoundException ex) {
            Logger.getLogger(yontoyuncuekleme.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(yontoyuncuekleme.class.getName()).log(Level.SEVERE, null, ex);
        }
       
   }
     public void idoyuncu() {
        try {
            pat=baglan.prepareStatement("SELECT id FROM oyuncu");
            rs=pat.executeQuery();
            txtoid.removeAllItems();
            while(rs.next()){
                txtoid.addItem(rs.getString(1));
            }
        } catch (SQLException ex) {
            Logger.getLogger(yontoyuncuekleme.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
     public void idmagaza() {
        try {
            pat=baglan.prepareStatement("SELECT id FROM magaza");
            rs=pat.executeQuery();
            txtmağid.removeAllItems();
            while(rs.next()){
                txtmağid.addItem(rs.getString(1));
            }
        } catch (SQLException ex) {
            Logger.getLogger(yontoyuncuekleme.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
       public void tablocalisanoyuncu(){
        try {
            pat=baglan.prepareStatement("SELECT*FROM oyuncu");
 
              rs=pat.executeQuery();
            ResultSetMetaData stveri=rs.getMetaData();
            q=stveri.getColumnCount();
            DefaultTableModel RecordTable=(DefaultTableModel)jTable1.getModel();
                    RecordTable.setRowCount(0);
             while(rs.next()){
                 Vector sutunVeri=new Vector();
                 for(i =1;i<=q;i++){
                     sutunVeri.add(rs.getString("id"));
                     sutunVeri.add(rs.getString("oyuncuAd"));
                     sutunVeri.add(rs.getString("oyuncuSoyad"));
                     sutunVeri.add(rs.getString("kullaniciAdi"));
                     sutunVeri.add(rs.getString("sifre"));
                      sutunVeri.add(rs.getString("yemekMik"));
                      sutunVeri.add(rs.getString("esyaMik"));
                      sutunVeri.add(rs.getString("paraMik"));
                      sutunVeri.add(rs.getString("calisma_bas_t"));
                      sutunVeri.add(rs.getString("calisma_bitis_t"));
                      sutunVeri.add(rs.getString("calisma_saat"));
                      sutunVeri.add(rs.getString("calisma_gün_s"));
                       sutunVeri.add(rs.getString("gunluk_k_para"));
                 }
                 RecordTable.addRow(sutunVeri);
                 
             }       
            
            
        } catch (SQLException ex) {
            Logger.getLogger(yontoyuncuekleme.class.getName()).log(Level.SEVERE, null, ex);
        }
      }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtmağid = new javax.swing.JComboBox<>();
        jBmagazalist = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        tx_ad = new javax.swing.JTextField();
        tx_soyad = new javax.swing.JTextField();
        tx_kullaniciAdi = new javax.swing.JTextField();
        tx_sifre = new javax.swing.JTextField();
        tx_yemekMik = new javax.swing.JTextField();
        tx_esyaMik = new javax.swing.JTextField();
        tx_paraMik = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        tx_esya_ucreti = new javax.swing.JTextField();
        tx_g_esya_gideri = new javax.swing.JTextField();
        tx_isletme_id = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        tx_calisma_bas_t = new javax.swing.JTextField();
        tx_calisma_bit_t = new javax.swing.JTextField();
        tx_calisma_s = new javax.swing.JTextField();
        tx_calisma_gun_s = new javax.swing.JTextField();
        tx_gunluk_k_para = new javax.swing.JTextField();
        tx_kazanc = new javax.swing.JTextField();
        jBanlaşma = new javax.swing.JButton();
        jBbilgiguncelleme = new javax.swing.JButton();
        jBsatis = new javax.swing.JButton();
        jBtemizle = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        txtoid = new javax.swing.JComboBox<>();
        jBlisteleoyuncu = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jBcıkıs = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("esya_ücreti:");

        jLabel2.setText("g_esya_gideri:");

        jLabel3.setText("isletme_id:");

        jLabel4.setText("magaza_id:");

        txtmağid.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jBmagazalist.setText("mağ.Listele");
        jBmagazalist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBmagazalistActionPerformed(evt);
            }
        });

        jLabel5.setText("AD:");

        jLabel6.setText("SOYAD:");

        jLabel7.setText("KULLANİCİ ADI:");

        jLabel8.setText("SİFRE:");

        jLabel9.setText("YEMEK MİK:");

        jLabel10.setText("ESYA MİK:");

        jLabel11.setText("PARA MİK:");

        tx_yemekMik.setToolTipText("");
        tx_yemekMik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tx_yemekMikActionPerformed(evt);
            }
        });

        jLabel12.setText("Çalişma_Baş_T:");

        jLabel13.setText("Çalişma_Bit_T:");

        jLabel14.setText("Çalişma Saat:");

        jLabel15.setText("Çalişma_Gün_S:");

        jLabel16.setText("Gunluk_k_para:");

        jLabel17.setText("Toplam_kazanc:");

        tx_gunluk_k_para.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tx_gunluk_k_paraActionPerformed(evt);
            }
        });

        tx_kazanc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tx_kazancActionPerformed(evt);
            }
        });

        jBanlaşma.setText("anlaşma");
        jBanlaşma.setToolTipText("");
        jBanlaşma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBanlaşmaActionPerformed(evt);
            }
        });

        jBbilgiguncelleme.setText("bilgi guncelleme");
        jBbilgiguncelleme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBbilgiguncellemeActionPerformed(evt);
            }
        });

        jBsatis.setText("satis");
        jBsatis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBsatisActionPerformed(evt);
            }
        });

        jBtemizle.setText("temizle");
        jBtemizle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtemizleActionPerformed(evt);
            }
        });

        jLabel18.setText("oyuncu id:");

        txtoid.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jBlisteleoyuncu.setText("Listele");
        jBlisteleoyuncu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBlisteleoyuncuActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "id", "ad", "soyad", "kullaniciAdi", "sifre", "yemekMik", "esyaMik", "paraMik", "calisma_bas_t", "calisma_bitis_t", "calisma_saat", "calisma_gün_s", "gunluk_k_para"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jBcıkıs.setText("cıkıs");
        jBcıkıs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBcıkısActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jBmagazalist)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtmağid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(153, 153, 153))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(tx_esya_ucreti, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(tx_g_esya_gideri, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(tx_isletme_id, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(177, 177, 177)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(45, 45, 45)
                                            .addComponent(tx_sifre, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(32, 32, 32)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(tx_ad, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(tx_soyad, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(45, 45, 45)
                                        .addComponent(tx_kullaniciAdi, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jBanlaşma)
                                    .addComponent(jBsatis))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jBtemizle)
                                        .addGap(46, 46, 46)
                                        .addComponent(jBcıkıs))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jBbilgiguncelleme)
                                        .addGap(201, 201, 201)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel11)
                                                .addGap(45, 45, 45)
                                                .addComponent(tx_paraMik, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel9)
                                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(32, 32, 32)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(tx_esyaMik, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(tx_yemekMik, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))))))
                        .addGap(31, 31, 31)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(122, 122, 122)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tx_calisma_bit_t, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tx_calisma_bas_t, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tx_calisma_s, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(tx_gunluk_k_para, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(tx_kazanc, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(35, 35, 35)
                                                .addComponent(txtoid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(109, 109, 109)
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tx_calisma_gun_s, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(128, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jBlisteleoyuncu)
                        .addGap(133, 133, 133))))
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1061, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5)
                    .addComponent(tx_ad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(tx_calisma_bas_t, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tx_esya_ucreti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6)
                    .addComponent(tx_soyad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(tx_g_esya_gideri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tx_calisma_bit_t, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(tx_isletme_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(tx_kullaniciAdi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)
                            .addComponent(tx_calisma_s, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tx_sifre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(tx_calisma_gun_s, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtmağid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBmagazalist)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(tx_yemekMik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel16)
                        .addComponent(tx_gunluk_k_para, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(tx_esyaMik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(tx_kazanc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(tx_paraMik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBanlaşma)
                    .addComponent(jBbilgiguncelleme)
                    .addComponent(jLabel18)
                    .addComponent(txtoid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtemizle)
                    .addComponent(jBsatis)
                    .addComponent(jBlisteleoyuncu)
                    .addComponent(jBcıkıs))
                .addGap(58, 58, 58)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(212, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tx_yemekMikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tx_yemekMikActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tx_yemekMikActionPerformed

    private void tx_gunluk_k_paraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tx_gunluk_k_paraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tx_gunluk_k_paraActionPerformed

    private void tx_kazancActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tx_kazancActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tx_kazancActionPerformed

    private void jBlisteleoyuncuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBlisteleoyuncuActionPerformed
        // TODO add your handling code here:
           try {
            // TODO add your handling code here:
            String oyuncuid=txtoid.getSelectedItem().toString();
            pat=baglan.prepareStatement("SELECT*FROM oyuncu WHERE id=?");
            pat.setString(1, oyuncuid);
            
            rs=pat.executeQuery();
            if(rs.next()==true){
                tx_ad.setText(rs.getString(2));
                tx_soyad.setText(rs.getString(3));
                tx_kullaniciAdi.setText(rs.getString(4));
                 tx_sifre.setText(rs.getString(5));
                 tx_yemekMik.setText(rs.getString(6));
                  tx_esyaMik.setText(rs.getString(7));
                   tx_paraMik.setText(rs.getString(8));
                   tx_calisma_bas_t.setText(rs.getString(9));
                 tx_calisma_bit_t.setText(rs.getString(10));
                 tx_calisma_s.setText(rs.getString(11));
                tx_calisma_gun_s.setText(rs.getString(12));
                tx_gunluk_k_para.setText(rs.getString(13));
              
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(yontoyuncuekleme.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jBlisteleoyuncuActionPerformed

    private void jBmagazalistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBmagazalistActionPerformed
        // TODO add your handling code here:
           try {
            // TODO add your handling code here:
            String marketid=txtmağid.getSelectedItem().toString();
            pat=baglan.prepareStatement("SELECT*FROM magaza WHERE id=?");
            pat.setString(1, marketid);
            
            rs=pat.executeQuery();
          
            if(rs.next()==true){
               tx_esya_ucreti.setText(rs.getString(2));
                tx_g_esya_gideri.setText(rs.getString(3));
               tx_isletme_id.setText(rs.getString(4));
                
                 
                 
              
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(yontoyuncuekleme.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jBmagazalistActionPerformed

    private void jBanlaşmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBanlaşmaActionPerformed
        // TODO add your handling code here:
          try {
            // TODO add your handling code here:
            String ad=tx_ad.getText();
            String soyad=tx_soyad.getText();
            String kullaniciAdi=tx_kullaniciAdi.getText();
            String sifre=String.valueOf(tx_sifre.getText());
            String yemekMik=tx_yemekMik.getText();
            String esyaMik=tx_esyaMik.getText();
            String paraMik=tx_paraMik.getText();
            
      String calisma_bas_t=tx_calisma_bas_t.getText();
       String calisma_bit_t=tx_calisma_bit_t.getText();
             String calisma_s=tx_calisma_s.getText();
             String calisma_gun_s = tx_calisma_gun_s.getText();
            String gunluk_k_para= tx_gunluk_k_para.getText();
             String oyuncuid=txtoid.getSelectedItem().toString();
            pat=baglan.prepareStatement("UPDATE oyuncu SET oyuncuAd=?,oyuncuSoyad=?,kullaniciAdi=?,sifre=?,yemekMik=?,esyaMik=?,paraMik=?,calisma_bas_t=?,calisma_bitis_t=?,calisma_saat=?,calisma_gün_s=?,gunluk_k_para=? WHERE id=?");
            pat.setString(1, ad);
            pat.setString(2, soyad);
            pat.setString(3, kullaniciAdi);
            pat.setString(4,sifre);
             pat.setString(5,yemekMik );
            pat.setString(6,esyaMik );
            pat.setString(7,paraMik);
             pat.setString(8,calisma_bas_t);
              pat.setString(9,calisma_bit_t);
               pat.setString(10,calisma_s);
                pat.setString(11,calisma_gun_s );
                pat.setString(12,gunluk_k_para );
                  pat.setString(13,oyuncuid );
            int k=pat.executeUpdate();
            tablocalisanoyuncu();
            if(k==1){
                JOptionPane.showMessageDialog(this, "veri tabani eklemesi basarili");
               
             
            }
            else{
                JOptionPane.showMessageDialog(this, "veri tabani eklemesi basarisiz");
            }
               
        } catch (SQLException ex) {
            Logger.getLogger(yontoyuncuekleme.class.getName()).log(Level.SEVERE, null, ex);
        }
          
    }//GEN-LAST:event_jBanlaşmaActionPerformed

    private void jBbilgiguncellemeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBbilgiguncellemeActionPerformed
        // TODO add your handling code here:
             Date gunbit=new Date();
      SimpleDateFormat f=new SimpleDateFormat("yyyy-MM-dd");
       Date gunbas=new Date();
      SimpleDateFormat f1=new SimpleDateFormat("yyyy-MM-dd");
        try {
            gunbit=f.parse(tx_calisma_bit_t.getText());
             gunbas=f1.parse(tx_calisma_bas_t.getText());
            
            
        } catch (ParseException ex) {
            Logger.getLogger(marketcalisma.class.getName()).log(Level.SEVERE, null, ex);
        }
      Long tarihfarki=(gunbit.getTime()-gunbas.getTime())/(1000*60*60*24);
        System.out.println("tarihfark."+tarihfarki);
     if(tarihfarki>0){
         int yeniYemekM=Integer.parseInt(tx_yemekMik.getText());
         yeniYemekM=(int) (yeniYemekM-tarihfarki);
          String yeniYemekMik =Integer.toString(yeniYemekM);
          if(yeniYemekM==0){
              delete();
          }
          int yeniParaM=Integer.parseInt(tx_paraMik.getText());
         yeniParaM=(int) (yeniParaM-tarihfarki);
          String yeniParaMik =Integer.toString(yeniParaM);
          if(yeniParaM==0){
              delete();
          }
          
          try {
                  String ad=tx_ad.getText();
            String soyad=tx_soyad.getText();
            String kullaniciAdi=tx_kullaniciAdi.getText();
            String sifre=String.valueOf(tx_sifre.getText());
            //String yemekMik=tx_yemekMik.getText();
            String esyaMik=tx_esyaMik.getText();
           // String paraMik=tx_paraMik.getText();
            
      String calisma_bas_t=tx_calisma_bas_t.getText();
       String calisma_bit_t=tx_calisma_bit_t.getText();
             String calisma_s=tx_calisma_s.getText();
             String calisma_gun_s = tx_calisma_gun_s.getText();
            String gunluk_k_para= tx_gunluk_k_para.getText();
            
            String oyuncuid=txtoid.getSelectedItem().toString();
             pat=baglan.prepareStatement("UPDATE oyuncu SET oyuncuAd=?,oyuncuSoyad=?,kullaniciAdi=?,sifre=?,yemekMik=?,esyaMik=?,paraMik=?,calisma_bas_t=?,calisma_bitis_t=?,calisma_saat=?,calisma_gün_s=?,gunluk_k_para=? WHERE id=?");
              
               pat.setString(1, ad);
            pat.setString(2, soyad);
            pat.setString(3, kullaniciAdi);
            pat.setString(4,sifre);
             pat.setString(5, yeniYemekMik );
            pat.setString(6,esyaMik );
            pat.setString(7,yeniParaMik);
             pat.setString(8,calisma_bas_t);
              pat.setString(9,calisma_bit_t);
               pat.setString(10,calisma_s);
                pat.setString(11,calisma_gun_s );
                pat.setString(12,gunluk_k_para );
                pat.setString(13,oyuncuid);
                
                int k=pat.executeUpdate();
                  tablocalisanoyuncu();
             int gunluk_kazanc= Integer.parseInt(tx_gunluk_k_para.getText());
           int tutar=(int) (tarihfarki*gunluk_kazanc);
             // System.out.println("fmfdm"+tutar);
            String kazanc= String.valueOf(tutar);
            tx_kazanc.setText(kazanc);
            if(k==1){
                JOptionPane.showMessageDialog(this, "veri tabani eklemesi basarili");
               
               /* tx_ad.setText("");
                tx_soyad.setText("");
                tx_kullaniciAdi.setText("");
                tx_sifre.setText("");
                tx_yemekMik.setText("");
                tx_esyaMik.setText("");
                tx_paraMik.setText("");
                  tx_calisma_bas_t.setText("");
                   tx_calisma_bit_t.setText("");
                    tx_calisma_s.setText("");
                     tx_calisma_gun_s.setText("");
                      tx_gunluk_k_para.setText("");
                      tx_ad.requestFocus();
               idoyuncu();*/
            }
          
          
           
              
          } catch (SQLException ex) {
              Logger.getLogger(marketcalisma.class.getName()).log(Level.SEVERE, null, ex);
          }
         
      }
  
    }//GEN-LAST:event_jBbilgiguncellemeActionPerformed

    private void jBsatisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBsatisActionPerformed
        // TODO add your handling code here:
         int esyaucreti =Integer.parseInt( tx_esya_ucreti.getText());
         int tkazanc =Integer.parseInt( tx_kazanc.getText());
          int yenitutar=(tkazanc-esyaucreti);
          String kazanc1= String.valueOf(yenitutar);
            tx_kazanc.setText(kazanc1);
    }//GEN-LAST:event_jBsatisActionPerformed

    private void jBtemizleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtemizleActionPerformed
        // TODO add your handling code here:
        veriTemizle();
    }//GEN-LAST:event_jBtemizleActionPerformed

    private void jBcıkısActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBcıkısActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jBcıkısActionPerformed
public void delete(){
    

         DefaultTableModel RecordTable=(DefaultTableModel)jTable1.getModel();
        int satirSec=jTable1.getSelectedRow();
     
       
              try {
             //int id=Integer.parseInt(RecordTable.getValueAt(satirSec, 0).toString());
               int id= Integer.parseInt(txtoid.getSelectedItem().toString());
       int delete=JOptionPane.showConfirmDialog(null,"silinsin","silme islemi",JOptionPane.YES_NO_OPTION);
        if(delete==JOptionPane.YES_OPTION){
                  pat=baglan.prepareStatement("DELETE FROM oyuncu WHERE id=?");
                  pat.setInt(1, id);
                  pat.execute();
                  tablocalisanoyuncu();
                  tx_ad.setText("");
                  tx_ad.requestFocus();
                  tx_soyad.setText("");
                  tx_kullaniciAdi.setText("");
                  tx_sifre.setText("");
                   tx_yemekMik.setText("");
                tx_esyaMik.setText("");
                tx_paraMik.setText("");
                     tx_calisma_bas_t.setText("");
                   tx_calisma_bit_t.setText("");
                    tx_calisma_s.setText("");
                     tx_calisma_gun_s.setText("");
                      tx_gunluk_k_para.setText("");
                  
                
        } 
              } catch (SQLException ex) {
                  Logger.getLogger(yontoyuncuekleme.class.getName()).log(Level.SEVERE, null, ex);
              }
}
public void veriTemizle(){
       tx_ad.setText("");
                tx_soyad.setText("");
                tx_kullaniciAdi.setText("");
                tx_sifre.setText("");
                tx_yemekMik.setText("");
                tx_esyaMik.setText("");
                tx_paraMik.setText("");
                  tx_calisma_bas_t.setText("");
                   tx_calisma_bit_t.setText("");
                    tx_calisma_s.setText("");
                     tx_calisma_gun_s.setText("");
                      tx_gunluk_k_para.setText("");
                         tx_ad.requestFocus();
               idoyuncu();
                 tx_esya_ucreti.setText("");
                tx_g_esya_gideri.setText("");
               tx_isletme_id.setText("");
                tx_esya_ucreti.setText("");
                idmagaza();
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(magazacalisma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(magazacalisma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(magazacalisma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(magazacalisma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new magazacalisma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBanlaşma;
    private javax.swing.JButton jBbilgiguncelleme;
    private javax.swing.JButton jBcıkıs;
    private javax.swing.JButton jBlisteleoyuncu;
    private javax.swing.JButton jBmagazalist;
    private javax.swing.JButton jBsatis;
    private javax.swing.JButton jBtemizle;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField tx_ad;
    private javax.swing.JTextField tx_calisma_bas_t;
    private javax.swing.JTextField tx_calisma_bit_t;
    private javax.swing.JTextField tx_calisma_gun_s;
    private javax.swing.JTextField tx_calisma_s;
    private javax.swing.JTextField tx_esyaMik;
    private javax.swing.JTextField tx_esya_ucreti;
    private javax.swing.JTextField tx_g_esya_gideri;
    private javax.swing.JTextField tx_gunluk_k_para;
    private javax.swing.JTextField tx_isletme_id;
    private javax.swing.JTextField tx_kazanc;
    private javax.swing.JTextField tx_kullaniciAdi;
    private javax.swing.JTextField tx_paraMik;
    private javax.swing.JTextField tx_sifre;
    private javax.swing.JTextField tx_soyad;
    private javax.swing.JTextField tx_yemekMik;
    private javax.swing.JComboBox<String> txtmağid;
    private javax.swing.JComboBox<String> txtoid;
    // End of variables declaration//GEN-END:variables
}
