
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Aylin
 */
public class market extends javax.swing.JFrame {

    /**
     * Creates new form market
     */
    public market() {
        initComponents();
        connection();
        idmarket();
        tablomarket();
        
    }
   Connection baglan; 
  PreparedStatement pat;
  ResultSet rs;
  int q,i;
   
   public void connection(){
       try{
       Class.forName("com.mysql.jdbc.Driver");
     String bag="jdbc:mysql://localhost:3306/new_proje";
     String username="root";
     String sifre="684217";
     baglan= DriverManager.getConnection(bag,username,sifre);
    JOptionPane.showMessageDialog(null, "veri tabani baglantisi basarili");
   
       }
       catch (ClassNotFoundException ex) {
            Logger.getLogger(yontoyuncuekleme.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(yontoyuncuekleme.class.getName()).log(Level.SEVERE, null, ex);
        }
       
   }
     public void tablomarket(){
        try {
            pat=baglan.prepareStatement("SELECT*FROM market");
 
              rs=pat.executeQuery();
            ResultSetMetaData stveri=rs.getMetaData();
            q=stveri.getColumnCount();
            DefaultTableModel RecordTable=(DefaultTableModel)jTMarket.getModel();
                    RecordTable.setRowCount(0);
             while(rs.next()){
                 Vector sutunVeri=new Vector();
                 for(i =1;i<=q;i++){
                     sutunVeri.add(rs.getString("id"));
                     sutunVeri.add(rs.getString("yiyecek_ucreti"));
                     sutunVeri.add(rs.getString("g_yiyecek_gideri"));
                     sutunVeri.add(rs.getString("isletme_id"));
             
                 }
                 RecordTable.addRow(sutunVeri);
                 
             }       
            
            
        } catch (SQLException ex) {
            Logger.getLogger(yontoyuncuekleme.class.getName()).log(Level.SEVERE, null, ex);
        }
      }
       public void idmarket() {
        try {
            pat=baglan.prepareStatement("SELECT id FROM market");
            rs=pat.executeQuery();
            txtmid.removeAllItems();
            while(rs.next()){
                txtmid.addItem(rs.getString(1));
            }
        } catch (SQLException ex) {
            Logger.getLogger(yontoyuncuekleme.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane4 = new javax.swing.JScrollPane();
        jTMarket = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tx_yiyecek_ucreti = new javax.swing.JTextField();
        tx_g_yiyecek_gideri = new javax.swing.JTextField();
        tx_isletme_id = new javax.swing.JTextField();
        jBekle = new javax.swing.JButton();
        jbgüncelle = new javax.swing.JButton();
        jbdelete = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtmid = new javax.swing.JComboBox<>();
        jBarama = new javax.swing.JButton();
        jbcıkıs = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTMarket.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "id", "yiyecek_ucreti", "g_yiyecek_gideri", "isletme_id"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane4.setViewportView(jTMarket);

        jLabel1.setText("yiyecek_ucreti:");

        jLabel2.setText("g_yiyecek_gideri:");

        jLabel3.setText("isletme_id:");

        tx_yiyecek_ucreti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tx_yiyecek_ucretiActionPerformed(evt);
            }
        });

        tx_g_yiyecek_gideri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tx_g_yiyecek_gideriActionPerformed(evt);
            }
        });

        jBekle.setText("EKLE");
        jBekle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBekleActionPerformed(evt);
            }
        });

        jbgüncelle.setText("GÜNCELLE");
        jbgüncelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbgüncelleActionPerformed(evt);
            }
        });

        jbdelete.setText("DELETE");
        jbdelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbdeleteActionPerformed(evt);
            }
        });

        jLabel4.setText("market_id:");

        txtmid.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jBarama.setText("ARA");
        jBarama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBaramaActionPerformed(evt);
            }
        });

        jbcıkıs.setText("cıkıs");
        jbcıkıs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbcıkısActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tx_g_yiyecek_gideri, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tx_yiyecek_ucreti, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tx_isletme_id, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(110, 110, 110)
                        .addComponent(jBekle)
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbgüncelle)
                                .addGap(31, 31, 31)
                                .addComponent(jbdelete))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jBarama)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(26, 26, 26)
                                        .addComponent(txtmid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(23, 23, 23)))
                        .addGap(18, 18, 18)
                        .addComponent(jbcıkıs))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 679, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(tx_yiyecek_ucreti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBekle)
                            .addComponent(jbgüncelle)
                            .addComponent(jbdelete)
                            .addComponent(jbcıkıs))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(tx_g_yiyecek_gideri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tx_isletme_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtmid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jBarama)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tx_yiyecek_ucretiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tx_yiyecek_ucretiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tx_yiyecek_ucretiActionPerformed

    private void tx_g_yiyecek_gideriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tx_g_yiyecek_gideriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tx_g_yiyecek_gideriActionPerformed

    private void jBaramaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBaramaActionPerformed
        // TODO add your handling code here:
           try {
            // TODO add your handling code here:
            String marketid=txtmid.getSelectedItem().toString();
            pat=baglan.prepareStatement("SELECT*FROM market WHERE id=?");
            pat.setString(1, marketid);
            
            rs=pat.executeQuery();
          
            if(rs.next()==true){
               tx_yiyecek_ucreti.setText(rs.getString(2));
                tx_g_yiyecek_gideri.setText(rs.getString(3));
               tx_isletme_id.setText(rs.getString(4));
                
                 
                 
              
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(yontoyuncuekleme.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jBaramaActionPerformed

    private void jBekleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBekleActionPerformed
        // TODO add your handling code here:
         try {
            // TODO add your handling code here:
            String yiyecek_ucreti=tx_yiyecek_ucreti.getText();
            String g_yiyecek_gideri=tx_g_yiyecek_gideri.getText();
            String isletme_id=tx_isletme_id.getText();
   
           
        
            
           
            
            pat=baglan.prepareStatement("INSERT INTO market(yiyecek_ucreti,g_yiyecek_gideri,isletme_id) VALUES(?,?,?)");
            pat.setString(1,yiyecek_ucreti);
            pat.setString(2, g_yiyecek_gideri);
            pat.setString(3, isletme_id);
            
           
            int k=pat.executeUpdate();
             tablomarket();
            if(k==1){
                JOptionPane.showMessageDialog(this, "veri tabani eklemesi basarili");
               
                tx_yiyecek_ucreti.setText("");
                tx_g_yiyecek_gideri.setText("");
                tx_isletme_id.setText("");
             
             
                  
            }
            else{
                JOptionPane.showMessageDialog(this, "veri tabani eklemesi basarisiz");
            }
               
        } catch (SQLException ex) {
            Logger.getLogger(yontoyuncuekleme.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jBekleActionPerformed

    private void jbgüncelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbgüncelleActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
      String yiyecek_ucreti=tx_yiyecek_ucreti.getText();
            String g_yiyecek_gideri=tx_g_yiyecek_gideri.getText();
            String isletme_id=tx_isletme_id.getText();
            
            String marketid=txtmid.getSelectedItem().toString();
            pat=baglan.prepareStatement("UPDATE market SET yiyecek_ucreti=?,g_yiyecek_gideri=?,isletme_id=? WHERE id=?");
           pat.setString(1,yiyecek_ucreti);
            pat.setString(2, g_yiyecek_gideri);
            pat.setString(3, isletme_id);
            pat.setString(4,marketid);
            
              int k=pat.executeUpdate();
            if(k==1){
              JOptionPane.showMessageDialog(this, "kayit basariyla guncellendi");
           tablomarket();
               
                   tx_yiyecek_ucreti.setText("");
                tx_g_yiyecek_gideri.setText("");
                tx_isletme_id.setText("");
                 tx_yiyecek_ucreti.requestFocus();
                idmarket();
                
                  
            }
        } catch (SQLException ex) {
            Logger.getLogger(yontoyuncuekleme.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbgüncelleActionPerformed

    private void jbdeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbdeleteActionPerformed
        // TODO add your handling code here:
                   DefaultTableModel RecordTable=(DefaultTableModel)jTMarket.getModel();
        int satirSec=jTMarket.getSelectedRow();
      
      
              try {
             int id=Integer.parseInt(RecordTable.getValueAt(satirSec, 0).toString());
       int delete=JOptionPane.showConfirmDialog(null,"silinsin","silme islemi",JOptionPane.YES_NO_OPTION);
        if(delete==JOptionPane.YES_OPTION){
                  pat=baglan.prepareStatement("DELETE FROM market WHERE id=?");
                  pat.setInt(1, id);
                  pat.execute();
                  tablomarket();
                   tx_yiyecek_ucreti.setText("");
                tx_g_yiyecek_gideri.setText("");
                tx_isletme_id.setText("");
                
                  
                
        } 
              } catch (SQLException ex) {
                  Logger.getLogger(yontoyuncuekleme.class.getName()).log(Level.SEVERE, null, ex);
              }
    }//GEN-LAST:event_jbdeleteActionPerformed

    private void jbcıkısActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbcıkısActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jbcıkısActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(market.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(market.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(market.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(market.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new market().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBarama;
    private javax.swing.JButton jBekle;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTMarket;
    private javax.swing.JButton jbcıkıs;
    private javax.swing.JButton jbdelete;
    private javax.swing.JButton jbgüncelle;
    private javax.swing.JTextField tx_g_yiyecek_gideri;
    private javax.swing.JTextField tx_isletme_id;
    private javax.swing.JTextField tx_yiyecek_ucreti;
    private javax.swing.JComboBox<String> txtmid;
    // End of variables declaration//GEN-END:variables
}
