
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Aylin
 */
public class marketcalisma extends javax.swing.JFrame {

    /**
     * Creates new form CALIŞMA
     */
    public marketcalisma() {
        initComponents();
        connection();
        tablocalisanoyuncu();
        idoyuncu();
        idmarket();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
        Connection baglan; 
  PreparedStatement pat;
  ResultSet rs;
  int q,i;
   
   public void connection(){
       try{
       Class.forName("com.mysql.jdbc.Driver");
     String bag="jdbc:mysql://localhost:3306/new_proje";
     String username="root";
     String sifre="684217";
     baglan= DriverManager.getConnection(bag,username,sifre);
    JOptionPane.showMessageDialog(null, "veri tabani baglantisi basarili");
   
       }
       catch (ClassNotFoundException ex) {
            Logger.getLogger(yontoyuncuekleme.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(yontoyuncuekleme.class.getName()).log(Level.SEVERE, null, ex);
        }
       
   }
   public void idoyuncu() {
        try {
            pat=baglan.prepareStatement("SELECT id FROM oyuncu");
            rs=pat.executeQuery();
            txtoid.removeAllItems();
            while(rs.next()){
                txtoid.addItem(rs.getString(1));
            }
        } catch (SQLException ex) {
            Logger.getLogger(yontoyuncuekleme.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
      public void idmarket() {
        try {
            pat=baglan.prepareStatement("SELECT id FROM market");
            rs=pat.executeQuery();
            txtmid.removeAllItems();
            while(rs.next()){
                txtmid.addItem(rs.getString(1));
            }
        } catch (SQLException ex) {
            Logger.getLogger(yontoyuncuekleme.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
       public void tablocalisanoyuncu(){
        try {
            pat=baglan.prepareStatement("SELECT*FROM oyuncu");
 
              rs=pat.executeQuery();
            ResultSetMetaData stveri=rs.getMetaData();
            q=stveri.getColumnCount();
            DefaultTableModel RecordTable=(DefaultTableModel)jTable1.getModel();
                    RecordTable.setRowCount(0);
             while(rs.next()){
                 Vector sutunVeri=new Vector();
                 for(i =1;i<=q;i++){
                     sutunVeri.add(rs.getString("id"));
                     sutunVeri.add(rs.getString("oyuncuAd"));
                     sutunVeri.add(rs.getString("oyuncuSoyad"));
                     sutunVeri.add(rs.getString("kullaniciAdi"));
                     sutunVeri.add(rs.getString("sifre"));
                      sutunVeri.add(rs.getString("yemekMik"));
                      sutunVeri.add(rs.getString("esyaMik"));
                      sutunVeri.add(rs.getString("paraMik"));
                      sutunVeri.add(rs.getString("calisma_bas_t"));
                      sutunVeri.add(rs.getString("calisma_bitis_t"));
                      sutunVeri.add(rs.getString("calisma_saat"));
                      sutunVeri.add(rs.getString("calisma_gün_s"));
                       sutunVeri.add(rs.getString("gunluk_k_para"));
                 }
                 RecordTable.addRow(sutunVeri);
                 
             }       
            
            
        } catch (SQLException ex) {
            Logger.getLogger(yontoyuncuekleme.class.getName()).log(Level.SEVERE, null, ex);
        }
      }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        tx_ad = new javax.swing.JTextField();
        tx_soyad = new javax.swing.JTextField();
        tx_kullaniciAdi = new javax.swing.JTextField();
        tx_sifre = new javax.swing.JTextField();
        tx_yemekMik = new javax.swing.JTextField();
        tx_esyaMik = new javax.swing.JTextField();
        tx_paraMik = new javax.swing.JTextField();
        tx_calisma_bas_t = new javax.swing.JTextField();
        tx_calisma_bit_t = new javax.swing.JTextField();
        tx_calisma_s = new javax.swing.JTextField();
        tx_calisma_gun_s = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        tx_yiyecek_ucreti = new javax.swing.JTextField();
        tx_g_yiyecek_gideri = new javax.swing.JTextField();
        tx_isletme_id = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jb_ara = new javax.swing.JButton();
        txtoid = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        txtmid = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jBanlasma = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        tx_gunluk_k_para = new javax.swing.JTextField();
        jBeksiltme = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        tx_kazanc = new javax.swing.JTextField();
        jBsatis = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jBveritemizle = new javax.swing.JButton();
        jBcıkıs = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("AD:");

        jLabel2.setText("SOYAD:");

        jLabel3.setText("KULLANİCİ ADİ:");

        jLabel4.setText("SİFRE:");

        jLabel5.setText("YEMEK MİK:");

        jLabel6.setText("ESYA MİK:");

        jLabel7.setText("PARA MİK:");

        jLabel8.setText("Çalişma Baş_T:");

        jLabel9.setText("Çalişma Bit_T:");

        jLabel10.setText("Çalişma Saat:");

        jLabel11.setText("Çalişma Gün_S:");

        tx_soyad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tx_soyadActionPerformed(evt);
            }
        });

        tx_paraMik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tx_paraMikActionPerformed(evt);
            }
        });

        tx_calisma_bas_t.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tx_calisma_bas_tActionPerformed(evt);
            }
        });

        jLabel12.setText("yiyecek_ücreti:");

        jLabel13.setText("g_yiyecek_gideri:");

        jLabel14.setText("isletme id:");

        jLabel15.setText("oyuncu id:");

        jb_ara.setText("Listele");
        jb_ara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_araActionPerformed(evt);
            }
        });

        txtoid.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel16.setText("market id:");

        txtmid.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton1.setText("M.Listele");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jBanlasma.setText("anlaşma");
        jBanlasma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBanlasmaActionPerformed(evt);
            }
        });

        jLabel17.setText("Gunluk_k_para:");

        jBeksiltme.setText("bilgi guncelleme");
        jBeksiltme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBeksiltmeActionPerformed(evt);
            }
        });

        jLabel18.setText("Toplam kazanc:");

        jBsatis.setText("SATİS");
        jBsatis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBsatisActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "id", "ad", "soyad", "kullaniciA", "sifre", "yemekMik", "esyaMik", "paraMik", "calisma_bas_t", "calisma_bits_t", "calisma_saat", "calisma_gün_s", "gunluk_k_para"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jBveritemizle.setText("temizle");
        jBveritemizle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBveritemizleActionPerformed(evt);
            }
        });

        jBcıkıs.setText("cıkıs");
        jBcıkıs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBcıkısActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(456, 456, 456)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel14))
                                .addGap(18, 18, 18))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton1)
                                    .addComponent(jBanlasma)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tx_isletme_id, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tx_g_yiyecek_gideri, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tx_yiyecek_ucreti, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtmid, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jBeksiltme)
                                .addGap(53, 53, 53)
                                .addComponent(jBsatis)
                                .addGap(47, 47, 47)
                                .addComponent(jBveritemizle)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tx_ad)
                            .addComponent(tx_soyad)
                            .addComponent(tx_esyaMik, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                            .addComponent(tx_yemekMik)
                            .addComponent(tx_sifre)
                            .addComponent(tx_paraMik)
                            .addComponent(tx_kullaniciAdi))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jb_ara)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel15)
                                        .addGap(30, 30, 30)
                                        .addComponent(txtoid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(66, 66, 66))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(1, 1, 1)
                                                .addComponent(jLabel18)
                                                .addGap(18, 18, 18)
                                                .addComponent(tx_kazanc, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel17)
                                                    .addComponent(jLabel11))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(tx_calisma_s, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(tx_calisma_gun_s, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                                                    .addComponent(tx_gunluk_k_para))))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel10)
                                            .addComponent(jLabel9))
                                        .addGap(18, 18, 18)
                                        .addComponent(tx_calisma_bit_t, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(18, 18, 18)
                                        .addComponent(tx_calisma_bas_t, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(199, 199, 199))))))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBcıkıs)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel8)
                            .addComponent(tx_calisma_bas_t, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tx_ad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel9)
                                            .addComponent(tx_calisma_bit_t, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(4, 4, 4)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel12)
                                            .addComponent(tx_yiyecek_ucreti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel10)
                                    .addComponent(tx_kullaniciAdi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tx_calisma_s, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(tx_soyad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(7, 7, 7)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel13)
                                    .addComponent(tx_g_yiyecek_gideri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel11)
                                    .addComponent(tx_sifre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tx_calisma_gun_s, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel14)
                                    .addComponent(tx_isletme_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(tx_yemekMik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17)
                            .addComponent(tx_gunluk_k_para, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(222, 222, 222)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(txtmid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(tx_esyaMik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel7)
                                            .addComponent(tx_paraMik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton1)
                                        .addGap(9, 9, 9))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel18)
                                    .addComponent(tx_kazanc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBanlasma)
                            .addComponent(jBeksiltme)
                            .addComponent(jBsatis)
                            .addComponent(jBveritemizle)
                            .addComponent(jBcıkıs))
                        .addGap(5, 5, 5))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtoid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))
                        .addGap(31, 31, 31)))
                .addComponent(jb_ara)
                .addGap(48, 48, 48)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(160, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tx_soyadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tx_soyadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tx_soyadActionPerformed

    private void tx_paraMikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tx_paraMikActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tx_paraMikActionPerformed

    private void tx_calisma_bas_tActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tx_calisma_bas_tActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tx_calisma_bas_tActionPerformed

    private void jb_araActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_araActionPerformed
        // TODO add your handling code here:
              try {
            // TODO add your handling code here:
            String oyuncuid=txtoid.getSelectedItem().toString();
            pat=baglan.prepareStatement("SELECT*FROM oyuncu WHERE id=?");
            pat.setString(1, oyuncuid);
            
            rs=pat.executeQuery();
            if(rs.next()==true){
                tx_ad.setText(rs.getString(2));
                tx_soyad.setText(rs.getString(3));
                tx_kullaniciAdi.setText(rs.getString(4));
                 tx_sifre.setText(rs.getString(5));
                 tx_yemekMik.setText(rs.getString(6));
                  tx_esyaMik.setText(rs.getString(7));
                   tx_paraMik.setText(rs.getString(8));
                   tx_calisma_bas_t.setText(rs.getString(9));
                 tx_calisma_bit_t.setText(rs.getString(10));
                 tx_calisma_s.setText(rs.getString(11));
                tx_calisma_gun_s.setText(rs.getString(12));
                tx_gunluk_k_para.setText(rs.getString(13));
              
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(yontoyuncuekleme.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jb_araActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
            try {
            // TODO add your handling code here:
            String marketid=txtmid.getSelectedItem().toString();
            pat=baglan.prepareStatement("SELECT*FROM market WHERE id=?");
            pat.setString(1, marketid);
            
            rs=pat.executeQuery();
          
            if(rs.next()==true){
               tx_yiyecek_ucreti.setText(rs.getString(2));
                tx_g_yiyecek_gideri.setText(rs.getString(3));
               tx_isletme_id.setText(rs.getString(4));
                
                 
                 
              
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(yontoyuncuekleme.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jBanlasmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBanlasmaActionPerformed
        // TODO add your handling code here:
          try {
            // TODO add your handling code here:
            String ad=tx_ad.getText();
            String soyad=tx_soyad.getText();
            String kullaniciAdi=tx_kullaniciAdi.getText();
            String sifre=String.valueOf(tx_sifre.getText());
            String yemekMik=tx_yemekMik.getText();
            String esyaMik=tx_esyaMik.getText();
            String paraMik=tx_paraMik.getText();
            
      String calisma_bas_t=tx_calisma_bas_t.getText();
       String calisma_bit_t=tx_calisma_bit_t.getText();
             String calisma_s=tx_calisma_s.getText();
             String calisma_gun_s = tx_calisma_gun_s.getText();
            String gunluk_k_para= tx_gunluk_k_para.getText();
             String oyuncuid=txtoid.getSelectedItem().toString();
            pat=baglan.prepareStatement("UPDATE oyuncu SET oyuncuAd=?,oyuncuSoyad=?,kullaniciAdi=?,sifre=?,yemekMik=?,esyaMik=?,paraMik=?,calisma_bas_t=?,calisma_bitis_t=?,calisma_saat=?,calisma_gün_s=?,gunluk_k_para=? WHERE id=?");
            pat.setString(1, ad);
            pat.setString(2, soyad);
            pat.setString(3, kullaniciAdi);
            pat.setString(4,sifre);
             pat.setString(5,yemekMik );
            pat.setString(6,esyaMik );
            pat.setString(7,paraMik);
             pat.setString(8,calisma_bas_t);
              pat.setString(9,calisma_bit_t);
               pat.setString(10,calisma_s);
                pat.setString(11,calisma_gun_s );
                pat.setString(12,gunluk_k_para );
                  pat.setString(13,oyuncuid );
            int k=pat.executeUpdate();
            tablocalisanoyuncu();
            if(k==1){
                JOptionPane.showMessageDialog(this, "veri tabani eklemesi basarili");
               
             
            }
            else{
                JOptionPane.showMessageDialog(this, "veri tabani eklemesi basarisiz");
            }
               
        } catch (SQLException ex) {
            Logger.getLogger(yontoyuncuekleme.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jBanlasmaActionPerformed
public void delete(){
    
// yemek yada esya miktari biteni oyundan atmak icinn
         DefaultTableModel RecordTable=(DefaultTableModel)jTable1.getModel();
        int satirSec=jTable1.getSelectedRow();
     
       
              try {
             //int id=Integer.parseInt(RecordTable.getValueAt(satirSec, 0).toString());
               int id= Integer.parseInt(txtoid.getSelectedItem().toString());
       int delete=JOptionPane.showConfirmDialog(null,"silinsin","silme islemi",JOptionPane.YES_NO_OPTION);
        if(delete==JOptionPane.YES_OPTION){
                  pat=baglan.prepareStatement("DELETE FROM oyuncu WHERE id=?");
                  pat.setInt(1, id);
                  pat.execute();
                  tablocalisanoyuncu();
                  tx_ad.setText("");
                  tx_ad.requestFocus();
                  tx_soyad.setText("");
                  tx_kullaniciAdi.setText("");
                  tx_sifre.setText("");
                   tx_yemekMik.setText("");
                tx_esyaMik.setText("");
                tx_paraMik.setText("");
                     tx_calisma_bas_t.setText("");
                   tx_calisma_bit_t.setText("");
                    tx_calisma_s.setText("");
                     tx_calisma_gun_s.setText("");
                      tx_gunluk_k_para.setText("");
                  
                
        } 
              } catch (SQLException ex) {
                  Logger.getLogger(yontoyuncuekleme.class.getName()).log(Level.SEVERE, null, ex);
              }
}

public void veriTemizle(){
       tx_ad.setText("");
                tx_soyad.setText("");
                tx_kullaniciAdi.setText("");
                tx_sifre.setText("");
                tx_yemekMik.setText("");
                tx_esyaMik.setText("");
                tx_paraMik.setText("");
                  tx_calisma_bas_t.setText("");
                   tx_calisma_bit_t.setText("");
                    tx_calisma_s.setText("");
                     tx_calisma_gun_s.setText("");
                      tx_gunluk_k_para.setText("");
                         tx_ad.requestFocus();
               idoyuncu();
                 tx_yiyecek_ucreti.setText("");
                tx_g_yiyecek_gideri.setText("");
               tx_isletme_id.setText("");
                tx_yiyecek_ucreti.setText("");
                idmarket();
}
    private void jBeksiltmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBeksiltmeActionPerformed
        // TODO add your handling code here:

             Date gunbit=new Date();
      SimpleDateFormat f=new SimpleDateFormat("yyyy-MM-dd");
       Date gunbas=new Date();
      SimpleDateFormat f1=new SimpleDateFormat("yyyy-MM-dd");
        try {
            gunbit=f.parse(tx_calisma_bit_t.getText());
             gunbas=f1.parse(tx_calisma_bas_t.getText());
            
            
        } catch (ParseException ex) {
            Logger.getLogger(marketcalisma.class.getName()).log(Level.SEVERE, null, ex);
        }
      Long tarihfarki=(gunbit.getTime()-gunbas.getTime())/(1000*60*60*24);
        System.out.println("tarihfark."+tarihfarki);
     if(tarihfarki>0){
         int yeniEsyaM=Integer.parseInt(tx_esyaMik.getText());
         yeniEsyaM=(int) (yeniEsyaM-tarihfarki);
          String yeniEsyaMik =Integer.toString(yeniEsyaM);
          if(yeniEsyaM==0){
              delete();
          }
          int yeniParaM=Integer.parseInt(tx_paraMik.getText());
         yeniParaM=(int) (yeniParaM-tarihfarki);
          String yeniParaMik =Integer.toString(yeniParaM);
          if(yeniParaM==0){
              delete();
          }
          
          try {
                  String ad=tx_ad.getText();
            String soyad=tx_soyad.getText();
            String kullaniciAdi=tx_kullaniciAdi.getText();
            String sifre=String.valueOf(tx_sifre.getText());
            String yemekMik=tx_yemekMik.getText();
           // String esyaMik=tx_esyaMik.getText();
           // String paraMik=tx_paraMik.getText();
            
      String calisma_bas_t=tx_calisma_bas_t.getText();
       String calisma_bit_t=tx_calisma_bit_t.getText();
             String calisma_s=tx_calisma_s.getText();
             String calisma_gun_s = tx_calisma_gun_s.getText();
            String gunluk_k_para= tx_gunluk_k_para.getText();
            
            String oyuncuid=txtoid.getSelectedItem().toString();
             pat=baglan.prepareStatement("UPDATE oyuncu SET oyuncuAd=?,oyuncuSoyad=?,kullaniciAdi=?,sifre=?,yemekMik=?,esyaMik=?,paraMik=?,calisma_bas_t=?,calisma_bitis_t=?,calisma_saat=?,calisma_gün_s=?,gunluk_k_para=? WHERE id=?");
              
               pat.setString(1, ad);
            pat.setString(2, soyad);
            pat.setString(3, kullaniciAdi);
            pat.setString(4,sifre);
             pat.setString(5,yemekMik );
            pat.setString(6,yeniEsyaMik );
            pat.setString(7,yeniParaMik);
             pat.setString(8,calisma_bas_t);
              pat.setString(9,calisma_bit_t);
               pat.setString(10,calisma_s);
                pat.setString(11,calisma_gun_s );
                pat.setString(12,gunluk_k_para );
                pat.setString(13,oyuncuid);
                
                int k=pat.executeUpdate();
                  tablocalisanoyuncu();
             int gunluk_kazanc= Integer.parseInt(tx_gunluk_k_para.getText());
           int tutar=(int) (tarihfarki*gunluk_kazanc);
             // System.out.println("fmfdm"+tutar);
            String kazanc= String.valueOf(tutar);
            tx_kazanc.setText(kazanc);
            if(k==1){
                JOptionPane.showMessageDialog(this, "veri tabani eklemesi basarili");
               
               /* tx_ad.setText("");
                tx_soyad.setText("");
                tx_kullaniciAdi.setText("");
                tx_sifre.setText("");
                tx_yemekMik.setText("");
                tx_esyaMik.setText("");
                tx_paraMik.setText("");
                  tx_calisma_bas_t.setText("");
                   tx_calisma_bit_t.setText("");
                    tx_calisma_s.setText("");
                     tx_calisma_gun_s.setText("");
                      tx_gunluk_k_para.setText("");
                      tx_ad.requestFocus();
               idoyuncu();*/
            }
          
          
           
              
          } catch (SQLException ex) {
              Logger.getLogger(marketcalisma.class.getName()).log(Level.SEVERE, null, ex);
          }
         
      }
  
      
        
    }//GEN-LAST:event_jBeksiltmeActionPerformed

    private void jBsatisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBsatisActionPerformed
        // TODO add your handling code here:
        
        int yiyecekucreti =Integer.parseInt( tx_yiyecek_ucreti.getText());
         int tkazanc =Integer.parseInt( tx_kazanc.getText());
          int yenitutar=(tkazanc-yiyecekucreti);
          String kazanc1= String.valueOf(yenitutar);
            tx_kazanc.setText(kazanc1);
    }//GEN-LAST:event_jBsatisActionPerformed

    private void jBveritemizleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBveritemizleActionPerformed
        // TODO add your handling code here:
        veriTemizle();
    }//GEN-LAST:event_jBveritemizleActionPerformed

    private void jBcıkısActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBcıkısActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jBcıkısActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(marketcalisma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(marketcalisma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(marketcalisma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(marketcalisma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new marketcalisma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBanlasma;
    private javax.swing.JButton jBcıkıs;
    private javax.swing.JButton jBeksiltme;
    private javax.swing.JButton jBsatis;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jBveritemizle;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jb_ara;
    private javax.swing.JTextField tx_ad;
    private javax.swing.JTextField tx_calisma_bas_t;
    private javax.swing.JTextField tx_calisma_bit_t;
    private javax.swing.JTextField tx_calisma_gun_s;
    private javax.swing.JTextField tx_calisma_s;
    private javax.swing.JTextField tx_esyaMik;
    private javax.swing.JTextField tx_g_yiyecek_gideri;
    private javax.swing.JTextField tx_gunluk_k_para;
    private javax.swing.JTextField tx_isletme_id;
    private javax.swing.JTextField tx_kazanc;
    private javax.swing.JTextField tx_kullaniciAdi;
    private javax.swing.JTextField tx_paraMik;
    private javax.swing.JTextField tx_sifre;
    private javax.swing.JTextField tx_soyad;
    private javax.swing.JTextField tx_yemekMik;
    private javax.swing.JTextField tx_yiyecek_ucreti;
    private javax.swing.JComboBox<String> txtmid;
    private javax.swing.JComboBox<String> txtoid;
    // End of variables declaration//GEN-END:variables
}
