/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Aylin
 */
public class oyuncucalismahak extends javax.swing.JFrame {

    /**
     * Creates new form oyuncusecim
     */
    public oyuncucalismahak() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBmarkt = new javax.swing.JButton();
        jBmagz = new javax.swing.JButton();
        jbtemlak = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jBmarkt.setText("market çalışma hakkı");
        jBmarkt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBmarktActionPerformed(evt);
            }
        });

        jBmagz.setText("mağaza çalışma hakkı");
        jBmagz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBmagzActionPerformed(evt);
            }
        });

        jbtemlak.setText("emlak çalişma hakkı");
        jbtemlak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtemlakActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtemlak)
                    .addComponent(jBmarkt)
                    .addComponent(jBmagz))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jBmarkt)
                .addGap(38, 38, 38)
                .addComponent(jBmagz)
                .addGap(41, 41, 41)
                .addComponent(jbtemlak)
                .addContainerGap(98, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtemlakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtemlakActionPerformed
        // TODO add your handling code here:
         new emlakislem().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jbtemlakActionPerformed

    private void jBmarktActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBmarktActionPerformed
        // TODO add your handling code here:
        new marketcalisma().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jBmarktActionPerformed

    private void jBmagzActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBmagzActionPerformed
        // TODO add your handling code here:
         new magazacalisma().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jBmagzActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(oyuncucalismahak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(oyuncucalismahak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(oyuncucalismahak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(oyuncucalismahak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new oyuncucalismahak().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBmagz;
    private javax.swing.JButton jBmarkt;
    private javax.swing.JButton jbtemlak;
    // End of variables declaration//GEN-END:variables
}
