
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Aylin
 */
public class tablooyuncu extends javax.swing.JFrame {

    /**
     * Creates new form tablooyuncu
     */
    public tablooyuncu() {
        initComponents();
          connection();
        tablocalisanoyuncu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
               Connection baglan; 
  PreparedStatement pat;
  ResultSet rs;
  int q,i;
   
   public void connection(){
       try{
       Class.forName("com.mysql.jdbc.Driver");
     String bag="jdbc:mysql://localhost:3306/new_proje";
     String username="root";
     String sifre="684217";
     baglan= DriverManager.getConnection(bag,username,sifre);
    JOptionPane.showMessageDialog(null, "veri tabani baglantisi basarili");
   
       }
       catch (ClassNotFoundException ex) {
            Logger.getLogger(yontoyuncuekleme.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(yontoyuncuekleme.class.getName()).log(Level.SEVERE, null, ex);
        }
       
   }
    public void tablocalisanoyuncu(){
        try {
            pat=baglan.prepareStatement("SELECT*FROM oyuncu");
 
              rs=pat.executeQuery();
            ResultSetMetaData stveri=rs.getMetaData();
            q=stveri.getColumnCount();
            DefaultTableModel RecordTable=(DefaultTableModel)jTable1.getModel();
                    RecordTable.setRowCount(0);
             while(rs.next()){
                 Vector sutunVeri=new Vector();
                 for(i =1;i<=q;i++){
                     sutunVeri.add(rs.getString("id"));
                     sutunVeri.add(rs.getString("oyuncuAd"));
                     sutunVeri.add(rs.getString("oyuncuSoyad"));
                     sutunVeri.add(rs.getString("kullaniciAdi"));
                     sutunVeri.add(rs.getString("sifre"));
                      sutunVeri.add(rs.getString("yemekMik"));
                      sutunVeri.add(rs.getString("esyaMik"));
                      sutunVeri.add(rs.getString("paraMik"));
                      sutunVeri.add(rs.getString("calisma_bas_t"));
                      sutunVeri.add(rs.getString("calisma_bitis_t"));
                      sutunVeri.add(rs.getString("calisma_saat"));
                      sutunVeri.add(rs.getString("calisma_gün_s"));
                       sutunVeri.add(rs.getString("gunluk_k_para"));
                 }
                 RecordTable.addRow(sutunVeri);
                 
             }       
            
            
        } catch (SQLException ex) {
            Logger.getLogger(yontoyuncuekleme.class.getName()).log(Level.SEVERE, null, ex);
        }
      }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jBcıkıs = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "id", "ad", "soyad", "kullaniciadi", "sifre", "yemekmik", "esyamik", "paramik", "calisma_bas_t", "calisma_bit_t", "calisma_saat", "calisma_g_s", "gunluk_k_para"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jBcıkıs.setText("çıkış");
        jBcıkıs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBcıkısActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1049, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jBcıkıs)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBcıkıs)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBcıkısActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBcıkısActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jBcıkısActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tablooyuncu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tablooyuncu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tablooyuncu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tablooyuncu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tablooyuncu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBcıkıs;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
