


import java.sql.SQLException;
import java.sql.DriverManager;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.sql.*;
import com.mysql.jdbc.Driver;
import java.util.Vector;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;





        
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Aylin
 */
public class yontoyuncuekleme extends javax.swing.JFrame {
 
    /**
     * Creates new form arayüz
     */
    public yontoyuncuekleme() {
        initComponents();
        baglantiAc();
        loadidoyuncu();
        tablo();
      
    }
    
  Connection baglan; 
  PreparedStatement pat;
  ResultSet rs;
  int q,i;
   
   public void baglantiAc(){
       try{
       Class.forName("com.mysql.jdbc.Driver");
     String bag="jdbc:mysql://localhost:3306/new_proje";
     String username="root";
     String sifre="684217";
     baglan= DriverManager.getConnection(bag,username,sifre);
    JOptionPane.showMessageDialog(null, "veri tabani baglantisi basarili");
   
       }
       catch (ClassNotFoundException ex) {
            Logger.getLogger(yontoyuncuekleme.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(yontoyuncuekleme.class.getName()).log(Level.SEVERE, null, ex);
        }
       
   }
      public void loadidoyuncu() {
        try {
            pat=baglan.prepareStatement("SELECT id FROM oyuncu");
            rs=pat.executeQuery();
            txtoid.removeAllItems();
            while(rs.next()){
                txtoid.addItem(rs.getString(1));
            }
        } catch (SQLException ex) {
            Logger.getLogger(yontoyuncuekleme.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
   /*public void baglantiKapat(){
       try{
         baglan.close();
       }
       catch(Exception e){
           JOptionPane.showMessageDialog(null, "veri tabani baglantisi kapandi");
       }
   }*/
      public void tablo(){
        try {
            pat=baglan.prepareStatement("SELECT*FROM oyuncu");
 
              rs=pat.executeQuery();
            ResultSetMetaData stveri=rs.getMetaData();
            q=stveri.getColumnCount();
            DefaultTableModel RecordTable=(DefaultTableModel)jTablo.getModel();
                    RecordTable.setRowCount(0);
             while(rs.next()){
                 Vector sutunVeri=new Vector();
                 for(i =1;i<=q;i++){
                     sutunVeri.add(rs.getString("id"));
                     sutunVeri.add(rs.getString("oyuncuAd"));
                     sutunVeri.add(rs.getString("oyuncuSoyad"));
                     sutunVeri.add(rs.getString("kullaniciAdi"));
                     sutunVeri.add(rs.getString("sifre"));
                      sutunVeri.add(rs.getString("yemekMik"));
                      sutunVeri.add(rs.getString("esyaMik"));
                      sutunVeri.add(rs.getString("paraMik"));
                 }
                 RecordTable.addRow(sutunVeri);
                 
             }       
            
            
        } catch (SQLException ex) {
            Logger.getLogger(yontoyuncuekleme.class.getName()).log(Level.SEVERE, null, ex);
        }
      }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tx_ad = new javax.swing.JTextField();
        tx_soyad = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jbekle = new javax.swing.JButton();
        jbguncelle = new javax.swing.JButton();
        jbdelete = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtoid = new javax.swing.JComboBox<>();
        jbarama = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        tx_kullaniciadi = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablo = new javax.swing.JTable();
        tx_sifre = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tx_yemekMik = new javax.swing.JTextField();
        tx_esyaMik = new javax.swing.JTextField();
        tx_paraMik = new javax.swing.JTextField();
        jBcikis = new javax.swing.JButton();
        jBcıkıs = new javax.swing.JButton();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jMenu1.setText("jMenu1");

        jMenuItem3.setText("jMenuItem3");

        jMenuItem4.setText("jMenuItem4");

        jMenuItem5.setText("jMenuItem5");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("AD:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("ŞİFRE:");

        tx_ad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tx_adActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("SOYAD:");

        jbekle.setText("ekle");
        jbekle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbekleActionPerformed(evt);
            }
        });

        jbguncelle.setText("guncelle");
        jbguncelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbguncelleActionPerformed(evt);
            }
        });

        jbdelete.setText("delete");
        jbdelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbdeleteActionPerformed(evt);
            }
        });

        jLabel5.setText("oyuncu Id");

        txtoid.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        txtoid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtoidActionPerformed(evt);
            }
        });

        jbarama.setText("arama");
        jbarama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbaramaActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("KULLANICI ADI:");

        jTablo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "idoyuncu", "oyuncuAd", "oyuncuSoyad", "kullaniciAdi", "sifre", "yemekMik", "esyaMik", "paraMik"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTablo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabloMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTablo);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("YEMEK MİK:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("ESYA MİK:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("PARA MİK:");

        tx_yemekMik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tx_yemekMikActionPerformed(evt);
            }
        });

        jBcikis.setText("next");
        jBcikis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBcikisActionPerformed(evt);
            }
        });

        jBcıkıs.setText("çıkıs");
        jBcıkıs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBcıkısActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(307, 307, 307)
                        .addComponent(jLabel5)
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtoid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbarama)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(27, 27, 27)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(45, 45, 45))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(jLabel6)
                                    .addGap(18, 18, 18)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tx_ad, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                            .addComponent(tx_soyad)
                            .addComponent(tx_kullaniciadi)
                            .addComponent(tx_sifre)
                            .addComponent(tx_yemekMik)
                            .addComponent(tx_esyaMik)
                            .addComponent(tx_paraMik, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 633, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbekle)
                                .addGap(32, 32, 32)
                                .addComponent(jbguncelle)
                                .addGap(37, 37, 37)
                                .addComponent(jbdelete)
                                .addGap(51, 51, 51)
                                .addComponent(jBcikis)
                                .addGap(32, 32, 32)
                                .addComponent(jBcıkıs)))))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(tx_ad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(tx_soyad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(jbarama))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtoid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tx_kullaniciadi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tx_sifre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tx_yemekMik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tx_esyaMik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tx_paraMik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbekle)
                    .addComponent(jbguncelle)
                    .addComponent(jbdelete)
                    .addComponent(jBcikis)
                    .addComponent(jBcıkıs))
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tx_adActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tx_adActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tx_adActionPerformed

    private void jbekleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbekleActionPerformed
        try {
            // TODO add your handling code here:
            String ad=tx_ad.getText();
            String soyad=tx_soyad.getText();
            String kullaniciAdi=tx_kullaniciadi.getText();
            String sifre=String.valueOf(tx_sifre.getPassword());
            String yemekMik=tx_yemekMik.getText();
            String esyaMik=tx_esyaMik.getText();
            String paraMik=tx_paraMik.getText();
            
           
            
            pat=baglan.prepareStatement("INSERT INTO oyuncu(oyuncuAd,oyuncuSoyad,kullaniciAdi,sifre,yemekMik,esyaMik,paraMik) VALUES(?,?,?,?,?,?,?)");
            pat.setString(1, ad);
            pat.setString(2, soyad);
            pat.setString(3, kullaniciAdi);
            pat.setString(4,sifre);
             pat.setString(5,yemekMik );
            pat.setString(6,esyaMik );
            pat.setString(7,paraMik);
            int k=pat.executeUpdate();
             tablo();
            if(k==1){
                JOptionPane.showMessageDialog(this, "veri tabani eklemesi basarili");
               
                tx_ad.setText("");
                tx_soyad.setText("");
                tx_kullaniciadi.setText("");
                tx_sifre.setText("");
                tx_yemekMik.setText("");
                tx_esyaMik.setText("");
                tx_paraMik.setText("");
                  
            }
            else{
                JOptionPane.showMessageDialog(this, "veri tabani eklemesi basarisiz");
            }
               
        } catch (SQLException ex) {
            Logger.getLogger(yontoyuncuekleme.class.getName()).log(Level.SEVERE, null, ex);
        }
       
        
    }//GEN-LAST:event_jbekleActionPerformed

    private void txtoidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtoidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtoidActionPerformed

    private void jbaramaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbaramaActionPerformed
        try {
            // TODO add your handling code here:
            String oyuncuid=txtoid.getSelectedItem().toString();
            pat=baglan.prepareStatement("SELECT*FROM oyuncu WHERE id=?");
            pat.setString(1, oyuncuid);
            
            rs=pat.executeQuery();
            if(rs.next()==true){
                tx_ad.setText(rs.getString(2));
                tx_soyad.setText(rs.getString(3));
                tx_kullaniciadi.setText(rs.getString(4));
                 tx_sifre.setText(rs.getString(5));
                 tx_yemekMik.setText(rs.getString(6));
                  tx_esyaMik.setText(rs.getString(7));
                   tx_paraMik.setText(rs.getString(8));
                 
              
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(yontoyuncuekleme.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbaramaActionPerformed

    private void jbguncelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbguncelleActionPerformed
        try {
            // TODO add your handling code here:
            String ad=tx_ad.getText();
            String soyad=tx_soyad.getText();
            String kullaniciAdi=tx_kullaniciadi.getText();
            String sifre=String.valueOf(tx_sifre.getPassword());
              String yemekMik=tx_yemekMik.getText();
            String esyaMik=tx_esyaMik.getText();
            String paraMik=tx_paraMik.getText();
            
            String oyuncuid=txtoid.getSelectedItem().toString();
            pat=baglan.prepareStatement("UPDATE oyuncu SET oyuncuAd=?,oyuncuSoyad=?,kullaniciAdi=?,sifre=?,yemekMik=?,esyaMik=?,paraMik=? WHERE id=?");
            pat.setString(1, ad);
            pat.setString(2, soyad);
            pat.setString(3, kullaniciAdi);
            pat.setString(4,sifre);
    
             pat.setString(5,yemekMik );
            pat.setString(6,esyaMik );
            pat.setString(7,paraMik);
            pat.setString(8,oyuncuid);
            
              int k=pat.executeUpdate();
            if(k==1){
              JOptionPane.showMessageDialog(this, "kayit basariyla guncellendi");
           tablo();
                tx_ad.setText("");
                tx_soyad.setText("");
                tx_kullaniciadi.setText("");
                tx_sifre.setText("");
                 tx_yemekMik.setText("");
                tx_esyaMik.setText("");
                tx_paraMik.setText("");
                tx_ad.requestFocus();
                loadidoyuncu();
                
                
                  
            }
        } catch (SQLException ex) {
            Logger.getLogger(yontoyuncuekleme.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbguncelleActionPerformed

    private void jbdeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbdeleteActionPerformed
        // TODO add your handling code here:
         DefaultTableModel RecordTable=(DefaultTableModel)jTablo.getModel();
        int satirSec=jTablo.getSelectedRow();
      
      
              try {
             int id=Integer.parseInt(RecordTable.getValueAt(satirSec, 0).toString());
       int delete=JOptionPane.showConfirmDialog(null,"silinsin","silme islemi",JOptionPane.YES_NO_OPTION);
        if(delete==JOptionPane.YES_OPTION){
                  pat=baglan.prepareStatement("DELETE FROM oyuncu WHERE id=?");
                  pat.setInt(1, id);
                  pat.execute();
                  tablo();
                  tx_ad.setText("");
                  tx_ad.requestFocus();
                  tx_soyad.setText("");
                  tx_kullaniciadi.setText("");
                  tx_sifre.setText("");
                   tx_yemekMik.setText("");
                tx_esyaMik.setText("");
                tx_paraMik.setText("");
                  
                
        } 
              } catch (SQLException ex) {
                  Logger.getLogger(yontoyuncuekleme.class.getName()).log(Level.SEVERE, null, ex);
              }
           
       
        
    }//GEN-LAST:event_jbdeleteActionPerformed

    private void jTabloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabloMouseClicked
        // TODO add your handling code here:
       DefaultTableModel RecordTable=(DefaultTableModel)jTablo.getModel();
        int satirSec=jTablo.getSelectedRow();
 
        tx_ad.setText(RecordTable.getValueAt(satirSec, 1).toString());
        tx_soyad.setText(RecordTable.getValueAt(satirSec, 2).toString());
        tx_kullaniciadi.setText(RecordTable.getValueAt(satirSec, 3).toString());
        tx_sifre.setText(RecordTable.getValueAt(satirSec, 5).toString());
        tx_yemekMik.setText(RecordTable.getValueAt(satirSec, 6).toString());
        tx_esyaMik.setText(RecordTable.getValueAt(satirSec, 7).toString());
        tx_paraMik.setText(RecordTable.getValueAt(satirSec, 8).toString());
        
    }//GEN-LAST:event_jTabloMouseClicked

    private void tx_yemekMikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tx_yemekMikActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tx_yemekMikActionPerformed

    private void jBcikisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBcikisActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new arsa().setVisible(true);
    }//GEN-LAST:event_jBcikisActionPerformed

    private void jBcıkısActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBcıkısActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jBcıkısActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(yontoyuncuekleme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(yontoyuncuekleme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(yontoyuncuekleme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(yontoyuncuekleme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new yontoyuncuekleme().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBcikis;
    private javax.swing.JButton jBcıkıs;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablo;
    private javax.swing.JButton jbarama;
    private javax.swing.JButton jbdelete;
    private javax.swing.JButton jbekle;
    private javax.swing.JButton jbguncelle;
    private javax.swing.JTextField tx_ad;
    private javax.swing.JTextField tx_esyaMik;
    private javax.swing.JTextField tx_kullaniciadi;
    private javax.swing.JTextField tx_paraMik;
    private javax.swing.JPasswordField tx_sifre;
    private javax.swing.JTextField tx_soyad;
    private javax.swing.JTextField tx_yemekMik;
    private javax.swing.JComboBox<String> txtoid;
    // End of variables declaration//GEN-END:variables

 
}
